export {};
import { qs, request, setError, loadJson, saveJson, touchRecent, copyShare } from "./shared-client";
type Slot={id:number;label:string};type Resp={id:string;name:string;slotIds:number[]};type Data={id:string;title:string;description:string;expiresAt:number;slots:Slot[];responses:Resp[];counts:Record<string,number>;responseCount:number};
const loading=qs<HTMLElement>("[data-loading]")!,create=qs<HTMLElement>("[data-create]")!,event=qs<HTMLElement>("[data-event]")!,notFound=qs<HTMLElement>("[data-not-found]")!;
const params=new URLSearchParams(location.search),id=params.get("id")??"";let current:Data|null=null;
const adminKey=(x:string)=>"utility-tools:availability:admin:"+x,responseKey=(x:string)=>"utility-tools:availability:response:"+x;
touchRecent({id:"availability-match",href:"/availability-match/",name:"空き時間マッチング",category:"share"});
const errors={at_least_two_slots:"候補時間を2件以上入力してください。",name_required:"名前を入力してください。",slots_required:"空いている時間を1件以上選択してください。",name_already_used:"同じ名前の回答があります。"} as Record<string,string>;
function initCreate(){loading.hidden=true;create.hidden=false;const f=qs<HTMLFormElement>("[data-create-form]")!,err=qs<HTMLElement>("[data-create-error]")!;f.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(f),slots=[...new Set(String(fd.get("slots")??"").split(/\r?\n/).map(v=>v.trim()).filter(Boolean))];if(slots.length<2){setError(err,"候補時間は2件以上必要です。");return}try{const r=await request("/api/collab/availability",{method:"POST",body:JSON.stringify({title:fd.get("title"),description:fd.get("description"),slots})},errors);localStorage.setItem(adminKey(r.id),r.adminToken);location.assign("/availability-match/?id="+r.id+"&created=1")}catch(x){setError(err,x instanceof Error?x.message:"作成に失敗しました。")}})}
function saved(){return loadJson<any|null>(responseKey(id),null)}
function render(){if(!current)return;const data=current;qs<HTMLElement>("[data-title]")!.textContent=data.title;const d=qs<HTMLElement>("[data-description]")!;d.textContent=data.description;d.hidden=!data.description;qs<HTMLElement>("[data-count]")!.textContent=data.responseCount+"人回答";qs<HTMLElement>("[data-expiry]")!.textContent="保存期限: "+new Date(data.expiresAt).toLocaleDateString("ja-JP");qs<HTMLInputElement>("[data-share-url]")!.value=location.origin+"/availability-match/?id="+id;qs<HTMLElement>("[data-created]")!.hidden=params.get("created")!=="1";qs<HTMLButtonElement>("[data-delete]")!.hidden=!localStorage.getItem(adminKey(id));const sv=saved(),mine=sv?data.responses.find(x=>x.id===sv.responseId):undefined;qs<HTMLInputElement>("[data-name]")!.value=mine?.name??"";qs<HTMLElement>("[data-answer-heading]")!.textContent=mine?"回答を編集":"空いている時間を選ぶ";qs<HTMLButtonElement>("[data-answer-submit]")!.textContent=mine?"回答を更新":"回答を送信";qs<HTMLButtonElement>("[data-answer-delete]")!.hidden=!mine;const slots=qs<HTMLElement>("[data-slots]")!;slots.replaceChildren();for(const s of data.slots){const l=document.createElement("label");l.className="slot-check";const i=document.createElement("input");i.type="checkbox";i.value=String(s.id);i.checked=mine?.slotIds.includes(s.id)??false;const sp=document.createElement("span");sp.textContent=s.label;l.append(i,sp);slots.append(l)}const out=qs<HTMLElement>("[data-results]")!;out.replaceChildren();const max=Math.max(1,data.responseCount);[...data.slots].sort((a,b)=>(data.counts[String(b.id)]??0)-(data.counts[String(a.id)]??0)).forEach(s=>{const c=data.counts[String(s.id)]??0,p=Math.round(c/max*100);const row=document.createElement("div");row.className="slot-result";row.innerHTML='<div class="slot-result-head"><span></span><strong></strong></div><div class="slot-result-bar"><span></span></div>';row.querySelector(".slot-result-head span")!.textContent=s.label;row.querySelector("strong")!.textContent=c+" / "+data.responseCount+"人";(row.querySelector(".slot-result-bar span") as HTMLElement).style.width=p+"%";out.append(row)})}
async function reload(){current=await request("/api/collab/availability/"+id,undefined,errors);render()}
function wire(){const f=qs<HTMLFormElement>("[data-answer-form]")!,err=qs<HTMLElement>("[data-answer-error]")!;f.addEventListener("submit",async e=>{e.preventDefault();const slotIds=[...document.querySelectorAll<HTMLInputElement>("[data-slots] input:checked")].map(x=>Number(x.value)),body={name:qs<HTMLInputElement>("[data-name]")!.value,slotIds},sv=saved();try{if(sv){await request("/api/collab/availability/"+id+"/availability-response/"+sv.responseId,{method:"PUT",headers:{authorization:"Bearer "+sv.editToken},body:JSON.stringify(body)},errors)}else{const r=await request("/api/collab/availability/"+id+"/availability-response",{method:"POST",body:JSON.stringify(body)},errors);saveJson(responseKey(id),{responseId:r.responseId,editToken:r.editToken})}await reload();setError(err)}catch(x){setError(err,x instanceof Error?x.message:"回答に失敗しました。")}});qs<HTMLButtonElement>("[data-answer-delete]")!.addEventListener("click",async()=>{const sv=saved();if(!sv||!confirm("回答を削除しますか？"))return;await request("/api/collab/availability/"+id+"/availability-response/"+sv.responseId,{method:"DELETE",headers:{authorization:"Bearer "+sv.editToken}},errors);localStorage.removeItem(responseKey(id));await reload()});qs<HTMLButtonElement>("[data-copy]")!.addEventListener("click",()=>copyShare(qs<HTMLInputElement>("[data-share-url]")!,qs<HTMLElement>("[data-copy-message]")!));qs<HTMLButtonElement>("[data-delete]")!.addEventListener("click",async()=>{const token=localStorage.getItem(adminKey(id));if(!token||!confirm("この候補時間を削除しますか？"))return;await request("/api/collab/availability/"+id,{method:"DELETE",headers:{authorization:"Bearer "+token}},errors);location.assign("/availability-match/")})}
if(id){wire();reload().then(()=>{loading.hidden=true;event.hidden=false}).catch(()=>{loading.hidden=true;notFound.hidden=false})}else initCreate();