export {};
import { qs, request, setError, loadJson, saveJson, touchRecent, copyShare } from "./shared-client";
type Option={id:number;label:string};type Result={optionId:number;label:string;score:number;firstPlaceVotes:number};type Data={id:string;title:string;description:string;expiresAt:number;options:Option[];results:Result[];totalVotes:number};
const loading=qs<HTMLElement>("[data-loading]")!,create=qs<HTMLElement>("[data-create]")!,event=qs<HTMLElement>("[data-event]")!,notFound=qs<HTMLElement>("[data-not-found]")!;
const params=new URLSearchParams(location.search),id=params.get("id")??"";let current:Data|null=null;
const adminKey=(x:string)=>"utility-tools:ranking:admin:"+x,voteKey=(x:string)=>"utility-tools:ranking:vote:"+x;
touchRecent({id:"candidate-ranking",href:"/candidate-ranking/",name:"候補ランキング作成",category:"share"});
const errors={at_least_two_options:"候補を2件以上入力してください。",invalid_ranking:"すべての候補を重複なく順位付けしてください。",response_limit:"回答上限に達しました。"} as Record<string,string>;
function saved(){return loadJson<any|null>(voteKey(id),null)}
function initCreate(){loading.hidden=true;create.hidden=false;const f=qs<HTMLFormElement>("[data-create-form]")!,err=qs<HTMLElement>("[data-create-error]")!;f.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(f),options=[...new Set(String(fd.get("options")??"").split(/\r?\n/).map(v=>v.trim()).filter(Boolean))].slice(0,10);if(options.length<2){setError(err,"候補は2件以上必要です。");return}try{const r=await request("/api/collab/ranking",{method:"POST",body:JSON.stringify({title:fd.get("title"),description:fd.get("description"),options})},errors);localStorage.setItem(adminKey(r.id),r.adminToken);location.assign("/candidate-ranking/?id="+r.id+"&created=1")}catch(x){setError(err,x instanceof Error?x.message:"作成に失敗しました。")}})}
function render(){if(!current)return;qs<HTMLElement>("[data-title]")!.textContent=current.title;const d=qs<HTMLElement>("[data-description]")!;d.textContent=current.description;d.hidden=!current.description;qs<HTMLElement>("[data-count]")!.textContent=current.totalVotes+"件回答";qs<HTMLElement>("[data-expiry]")!.textContent="保存期限: "+new Date(current.expiresAt).toLocaleDateString("ja-JP");qs<HTMLInputElement>("[data-share-url]")!.value=location.origin+"/candidate-ranking/?id="+id;qs<HTMLElement>("[data-created]")!.hidden=params.get("created")!=="1";qs<HTMLButtonElement>("[data-delete]")!.hidden=!localStorage.getItem(adminKey(id));const sv=saved(),old:number[]=sv?.ranking??current.options.map(o=>o.id);const form=qs<HTMLElement>("[data-ranking-form]")!;form.replaceChildren();for(let rank=0;rank<current.options.length;rank++){const row=document.createElement("div");row.className="ranking-row";const b=document.createElement("b");b.textContent=(rank+1)+"位";const sel=document.createElement("select");sel.dataset.rank=String(rank);for(const o of current.options){const op=document.createElement("option");op.value=String(o.id);op.textContent=o.label;op.selected=old[rank]===o.id;sel.append(op)}row.append(b,sel);form.append(row)}qs<HTMLElement>("[data-answer-heading]")!.textContent=sv?"回答を変更":"順位を付ける";qs<HTMLButtonElement>("[data-submit]")!.textContent=sv?"回答を更新":"回答を送信";qs<HTMLButtonElement>("[data-delete-answer]")!.hidden=!sv;const out=qs<HTMLElement>("[data-results]")!;out.replaceChildren();current.results.forEach((r,i)=>{const row=document.createElement("div");row.className="ranking-result";const n=document.createElement("b");n.textContent=String(i+1);const label=document.createElement("strong");label.textContent=r.label;const score=document.createElement("span");score.textContent=r.score+"点";row.append(n,label,score);out.append(row)})}
async function reload(){current=await request("/api/collab/ranking/"+id,undefined,errors);render()}
function collect(){const vals=[...document.querySelectorAll<HTMLSelectElement>("[data-rank]")].map(s=>Number(s.value));return new Set(vals).size===vals.length?vals:null}
function wire(){const f=qs<HTMLFormElement>("[data-answer-form]")!,err=qs<HTMLElement>("[data-answer-error]")!;f.addEventListener("submit",async e=>{e.preventDefault();const ranking=collect();if(!ranking){setError(err,"同じ候補が重複しています。");return}const sv=saved();try{if(sv){await request("/api/collab/ranking/"+id+"/rank/"+sv.voteId,{method:"PUT",headers:{authorization:"Bearer "+sv.editToken},body:JSON.stringify({ranking})},errors);sv.ranking=ranking;saveJson(voteKey(id),sv)}else{const r=await request("/api/collab/ranking/"+id+"/rank",{method:"POST",body:JSON.stringify({ranking})},errors);saveJson(voteKey(id),{voteId:r.voteId,editToken:r.editToken,ranking})}setError(err);await reload()}catch(x){setError(err,x instanceof Error?x.message:"回答に失敗しました。")}});qs<HTMLButtonElement>("[data-delete-answer]")!.addEventListener("click",async()=>{const sv=saved();if(!sv||!confirm("回答を取り消しますか？"))return;await request("/api/collab/ranking/"+id+"/rank/"+sv.voteId,{method:"DELETE",headers:{authorization:"Bearer "+sv.editToken}},errors);localStorage.removeItem(voteKey(id));await reload()});qs<HTMLButtonElement>("[data-copy]")!.addEventListener("click",()=>copyShare(qs<HTMLInputElement>("[data-share-url]")!,qs<HTMLElement>("[data-copy-message]")!));qs<HTMLButtonElement>("[data-delete]")!.addEventListener("click",async()=>{const token=localStorage.getItem(adminKey(id));if(!token||!confirm("このランキングを削除しますか？"))return;await request("/api/collab/ranking/"+id,{method:"DELETE",headers:{authorization:"Bearer "+token}},errors);location.assign("/candidate-ranking/")})}
if(id){wire();reload().then(()=>{loading.hidden=true;event.hidden=false}).catch(()=>{loading.hidden=true;notFound.hidden=false})}else initCreate();