type Player = {
  id:string; name:string; nation:string; age:number; pos:string[]; ovr:number; pot:number;
  pac:number; sho:number; pas:number; dri:number; def:number; phy:number; price:number; value:number; wage:number;
  form:number; fit:number; dev:number; apps:number; starts:number; goals:number; assists:number; mom:number; injury:number;
  scouted:boolean; trait:string; clubId:string; clubName:string; country:string; contractYears:number; desiredWage:number;
  role:string; transferListed:boolean; ratingTotal:number; avgRating:number;
};
type Club = { id:string; name:string; country:string; ovr:number; league:boolean; flag:string };
type Offer = { id:string; playerId:string; clubId:string; clubName:string; amount:number; countered:boolean; final:boolean; status:string };
type Negotiation = { playerId:string; phase:"club"|"contract"; offer:number; ask:number; fee:number; wage:number; years:number; rounds:number; renewal:boolean; message:string };

type TableRow = { id:number; name:string; ovr:number; p:number; w:number; d:number; l:number; gf:number; ga:number; pts:number };

const root=document.querySelector<HTMLElement>('[data-mode="football-club-sim"]')!;
if(!root) throw new Error("football simulator root not found");
const intro=root.querySelector<HTMLElement>("[data-intro]")!, play=root.querySelector<HTMLElement>("[data-play]")!;
const KEY="utility-tools:sim:football-club-sim:v5", LEGACY_KEY="utility-tools:sim:football-club-sim:v4", BEST="utility-tools:sim:football-club-sim:best";
const TOTAL_MATCHES=38, USER_CLUB_ID="harbor", facilityCosts:any={training:1e8,recovery:8e7,academy:12e7,stadium:15e7};
const yen=(n:number)=>"¥"+Math.round(n).toLocaleString("ja-JP"), clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n)), ri=(a:number,b:number)=>Math.floor(a+Math.random()*(b-a+1));
const q=(x:string)=>root.querySelector<HTMLElement>(x)!, qb=(x:string)=>root.querySelector<HTMLButtonElement>(x)!, qs=(x:string)=>root.querySelector<HTMLSelectElement>(x)!;
const esc=(v:any)=>String(v??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));const baseTemplates:any[]=[
 {pos:["GK"],ovr:69,pac:42,sho:12,pas:61,dri:46,def:18,phy:70},{pos:["LB","LWB"],ovr:67,pac:75,sho:42,pas:65,dri:68,def:66,phy:64},
 {pos:["CB"],ovr:69,pac:61,sho:28,pas:57,dri:50,def:73,phy:76},{pos:["CB","RB"],ovr:68,pac:68,sho:31,pas:60,dri:58,def:70,phy:72},
 {pos:["RB","RWB"],ovr:67,pac:78,sho:40,pas:63,dri:67,def:64,phy:62},{pos:["CM","DM"],ovr:69,pac:65,sho:61,pas:74,dri:71,def:65,phy:66},
 {pos:["CM","AM"],ovr:68,pac:70,sho:65,pas:72,dri:73,def:48,phy:59},{pos:["CM","DM"],ovr:67,pac:62,sho:55,pas:70,dri:66,def:67,phy:69},
 {pos:["LW","RW"],ovr:70,pac:82,sho:69,pas:66,dri:78,def:31,phy:58},{pos:["ST"],ovr:71,pac:75,sho:77,pas:58,dri:70,def:25,phy:71},
 {pos:["RW","LW"],ovr:69,pac:81,sho:68,pas:64,dri:76,def:29,phy:56},{pos:["GK"],ovr:64,pac:37,sho:10,pas:57,dri:40,def:16,phy:65},
 {pos:["CB"],ovr:65,pac:55,sho:26,pas:54,dri:46,def:69,phy:74},{pos:["LB","RB"],ovr:64,pac:74,sho:36,pas:59,dri:63,def:61,phy:58},
 {pos:["CM","DM"],ovr:66,pac:61,sho:57,pas:69,dri:64,def:64,phy:67},{pos:["AM","CM"],ovr:66,pac:69,sho:64,pas:70,dri:71,def:38,phy:55},
 {pos:["ST","LW"],ovr:66,pac:72,sho:70,pas:53,dri:65,def:24,phy:69},{pos:["RW","AM"],ovr:65,pac:79,sho:61,pas:63,dri:72,def:27,phy:52}
];
const premiumTemplates:any[]=[
 {pos:["ST","RW"],ovr:73,pac:79,sho:78,pas:62,dri:74,def:27,phy:70},{pos:["CM","AM"],ovr:75,pac:70,sho:69,pas:81,dri:79,def:58,phy:65},
 {pos:["CB"],ovr:76,pac:67,sho:31,pas:66,dri:57,def:82,phy:81},{pos:["LW","RW"],ovr:77,pac:91,sho:75,pas:70,dri:84,def:29,phy:67},
 {pos:["AM","RW"],ovr:72,pac:82,sho:69,pas:75,dri:83,def:30,phy:55},{pos:["GK"],ovr:74,pac:44,sho:11,pas:68,dri:49,def:19,phy:76},
 {pos:["DM","CM"],ovr:74,pac:66,sho:54,pas:78,dri:72,def:75,phy:73},{pos:["ST"],ovr:71,pac:78,sho:75,pas:55,dri:73,def:20,phy:66},
 {pos:["CB","DM"],ovr:72,pac:58,sho:35,pas:66,dri:55,def:77,phy:80},{pos:["RB","RWB"],ovr:73,pac:86,sho:46,pas:69,dri:74,def:70,phy:71},
 {pos:["LB","LWB"],ovr:72,pac:84,sho:43,pas:70,dri:75,def:68,phy:64},{pos:["ST"],ovr:75,pac:69,sho:83,pas:58,dri:69,def:23,phy:82}
];
const allTemplates=[...baseTemplates,...premiumTemplates];const firstNames=["Ren","Haru","Sota","Kai","Leo","Noah","Luca","Mateo","Elias","Theo","Finn","Milan","Hugo","Niko","Emil","Rui","Jun","Kei","Toma","Yuki","Alex","Oscar","Bruno","Dario","Samir","Louis","Marco","Daniel","Jin","Aiden","Riku","Kota","Enzo","Ivan","Mika","Luis","Adrian","Fabio","Victor","Mauro","Jonas","Pablo","Nils","Tiago"];
const lastNames=["Arai","Kudo","Mori","Tanaka","Sato","Kobayashi","Ito","Seo","Park","Vale","Finch","Marin","Ward","Bauer","Costa","Keller","Navarro","Diaz","Okafor","Leclerc","Petrov","Reyes","Ferreira","Hansen","Rossi","Silva","Mendes","Lund","Bennett","Varga","Nwosu","Adebayo","Moretti","Dubois","Santos","Kim","Garcia","Fischer","Novak","Andersen","Romano","Vidal","Kovac","Pereira","Schmidt","Laurent"];
const nations=["🇯🇵","🇰🇷","🇬🇧","🇪🇸","🇵🇹","🇩🇪","🇫🇷","🇮🇹","🇧🇷","🇦🇷","🇳🇬","🇬🇭","🇩🇰","🇸🇪","🇷🇸","🇲🇽","🇺🇸","🇨🇦","🇦🇺","🇭🇺","🇳🇱","🇧🇪","🇨🇭","🇭🇷"];
const formations:any={
 "433":[["GK",7,44],["LB",23,12],["CB",23,35],["CB",23,59],["RB",23,82],["CM",49,22],["CM",49,49],["CM",49,76],["LW",78,14],["ST",83,49],["RW",78,84]],
 "4231":[["GK",7,44],["LB",23,12],["CB",23,35],["CB",23,59],["RB",23,82],["DM",45,34],["DM",45,64],["LW",66,15],["AM",63,49],["RW",66,83],["ST",84,49]],
 "343":[["GK",7,44],["CB",24,22],["CB",24,49],["CB",24,76],["LM",49,9],["CM",49,38],["CM",49,62],["RM",49,90],["LW",78,16],["ST",83,49],["RW",78,82]],
 "532":[["GK",7,44],["LWB",22,6],["CB",22,27],["CB",22,49],["CB",22,71],["RWB",22,92],["CM",51,23],["CM",51,49],["CM",51,75],["ST",82,35],["ST",82,65]]
};
const leagueClubs:Club[]=[
 {id:"0",name:"Harbor City FC",country:"LEAGUE",ovr:68,league:true,flag:"🏠"},{id:"1",name:"Northbridge United",country:"LEAGUE",ovr:70,league:true,flag:"🔵"},{id:"2",name:"Blue Coast FC",country:"LEAGUE",ovr:72,league:true,flag:"🌊"},{id:"3",name:"Redwood Athletic",country:"LEAGUE",ovr:67,league:true,flag:"🔴"},{id:"4",name:"Metro Stars",country:"LEAGUE",ovr:76,league:true,flag:"⭐"},
 {id:"5",name:"Riverside 04",country:"LEAGUE",ovr:66,league:true,flag:"🟢"},{id:"6",name:"Crown Town",country:"LEAGUE",ovr:71,league:true,flag:"👑"},{id:"7",name:"West Bay",country:"LEAGUE",ovr:69,league:true,flag:"🟡"},{id:"8",name:"Eastgate Rovers",country:"LEAGUE",ovr:68,league:true,flag:"⚪"},{id:"9",name:"Kingsford FC",country:"LEAGUE",ovr:74,league:true,flag:"🦁"},
 {id:"10",name:"Stonehaven",country:"LEAGUE",ovr:65,league:true,flag:"🪨"},{id:"11",name:"Greenwich Albion",country:"LEAGUE",ovr:70,league:true,flag:"🌿"},{id:"12",name:"Ironworks City",country:"LEAGUE",ovr:73,league:true,flag:"⚙️"},{id:"13",name:"Silverlake FC",country:"LEAGUE",ovr:67,league:true,flag:"⚪"},{id:"14",name:"Old Port Wanderers",country:"LEAGUE",ovr:69,league:true,flag:"⚓"},
 {id:"15",name:"Royal Borough",country:"LEAGUE",ovr:75,league:true,flag:"🟣"},{id:"16",name:"Forest Vale",country:"LEAGUE",ovr:66,league:true,flag:"🌲"},{id:"17",name:"Capital Athletic",country:"LEAGUE",ovr:72,league:true,flag:"🏙️"},{id:"18",name:"Seaside Town",country:"LEAGUE",ovr:68,league:true,flag:"🌅"},{id:"19",name:"Northern Lights",country:"LEAGUE",ovr:71,league:true,flag:"✨"}
];const foreignClubs:Club[]=[
 {id:"es1",name:"Costa Azul CF",country:"Spain",ovr:78,league:false,flag:"🇪🇸"},{id:"es2",name:"Real Sierra",country:"Spain",ovr:75,league:false,flag:"🇪🇸"},{id:"es3",name:"Valencia Norte",country:"Spain",ovr:73,league:false,flag:"🇪🇸"},{id:"es4",name:"Club del Sol",country:"Spain",ovr:71,league:false,flag:"🇪🇸"},
 {id:"it1",name:"Milano Rosso",country:"Italy",ovr:79,league:false,flag:"🇮🇹"},{id:"it2",name:"Torino Verde",country:"Italy",ovr:75,league:false,flag:"🇮🇹"},{id:"it3",name:"Roma Aurea",country:"Italy",ovr:74,league:false,flag:"🇮🇹"},{id:"it4",name:"Napoli Blu",country:"Italy",ovr:72,league:false,flag:"🇮🇹"},
 {id:"de1",name:"Rhein Adler",country:"Germany",ovr:79,league:false,flag:"🇩🇪"},{id:"de2",name:"Berlin 09",country:"Germany",ovr:76,league:false,flag:"🇩🇪"},{id:"de3",name:"Bavaria Rot",country:"Germany",ovr:80,league:false,flag:"🇩🇪"},{id:"de4",name:"Hanseatic SV",country:"Germany",ovr:72,league:false,flag:"🇩🇪"},
 {id:"fr1",name:"Paris Lumiere",country:"France",ovr:80,league:false,flag:"🇫🇷"},{id:"fr2",name:"Lyonnais Bleu",country:"France",ovr:75,league:false,flag:"🇫🇷"},{id:"fr3",name:"Marseille Sud",country:"France",ovr:74,league:false,flag:"🇫🇷"},{id:"fr4",name:"Monaco Etoile",country:"France",ovr:77,league:false,flag:"🇫🇷"},
 {id:"pt1",name:"Lisboa Branco",country:"Portugal",ovr:76,league:false,flag:"🇵🇹"},{id:"pt2",name:"Porto Azul",country:"Portugal",ovr:77,league:false,flag:"🇵🇹"},{id:"pt3",name:"Braga Norte",country:"Portugal",ovr:72,league:false,flag:"🇵🇹"},{id:"pt4",name:"Coimbra Academica",country:"Portugal",ovr:69,league:false,flag:"🇵🇹"},
 {id:"nl1",name:"Amsterdam Oranje",country:"Netherlands",ovr:76,league:false,flag:"🇳🇱"},{id:"nl2",name:"Rotterdam Zuid",country:"Netherlands",ovr:75,league:false,flag:"🇳🇱"},{id:"nl3",name:"Eindhoven Licht",country:"Netherlands",ovr:78,league:false,flag:"🇳🇱"},{id:"nl4",name:"Utrecht Dom",country:"Netherlands",ovr:70,league:false,flag:"🇳🇱"}
];
const allClubs=[...leagueClubs.slice(1),...foreignClubs], countries=["LEAGUE","Spain","Italy","Germany","France","Portugal","Netherlands"];

function seeded(seed:number){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function hashText(text:string){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function newSeed(){try{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]||Date.now()}catch{return Date.now()+Math.floor(Math.random()*1e7)}}
function traitFor(p:any){if(p.pac>=86)return"スピードスター";if(p.sho>=80)return"フィニッシャー";if(p.pas>=80)return"司令塔";if(p.def>=79)return"ボールハンター";if(p.phy>=80)return"フィジカル";if(p.dri>=80)return"ドリブラー";return"万能型"}
function marketValue(p:any){const age=p.age<=21?1.2:p.age>=31?.72:1,potBonus=1+Math.max(0,p.pot-p.ovr)*.032;return Math.round(Math.max(12000000,(p.ovr-55)**2*650000*age*potBonus)/1000000)*1000000}
function wageFor(p:any){return Math.round((250000+Math.max(0,p.ovr-62)*55000+(p.ovr>=78?300000:0))/10000)*10000}
function positionGroup(pos:string){if(pos==="GK")return"GK";if(["LB","CB","RB","LWB","RWB"].includes(pos))return"DF";if(["DM","CM","AM","LM","RM"].includes(pos))return"MF";return"FW"}function makePlayer(t:any,id:string,rnd:()=>number,club:Club|{id:string;name:string;country:string},targetOvr:number,owned=false):Player{
  const rr=(a:number,b:number)=>Math.floor(a+rnd()*(b-a+1)), pick=<T,>(a:T[])=>a[Math.floor(rnd()*a.length)];
  const age=rr(18,33), base=clamp(targetOvr+rr(-4,4),59,84), delta=base-t.ovr, vary=(v:number)=>clamp(v+delta+rr(-4,4),8,96);
  let pot=base+(age<=20?rr(8,16):age<=23?rr(5,13):age<=27?rr(2,8):rr(0,3));pot=clamp(pot,base,93);
  const p:any={id,name:pick(firstNames)+" "+pick(lastNames),nation:pick(nations),age,pos:[...t.pos],ovr:base,pot,pac:vary(t.pac),sho:vary(t.sho),pas:vary(t.pas),dri:vary(t.dri),def:vary(t.def),phy:vary(t.phy),price:0,value:0,wage:0,form:3,fit:rr(86,100),dev:rr(0,35),apps:0,starts:0,goals:0,assists:0,mom:0,injury:0,scouted:owned,trait:"",clubId:club.id,clubName:club.name,country:club.country,contractYears:rr(2,5),desiredWage:0,role:base>=78?"KEY":base>=72?"FIRST":"SQUAD",transferListed:false,ratingTotal:0,avgRating:0};
  p.trait=traitFor(p);p.value=marketValue(p);p.wage=wageFor(p);p.desiredWage=Math.round(p.wage*(1.04+rnd()*.16)/10000)*10000;return p;
}
function generateClubSquad(club:Club,seed:number,count=20){
  const rnd=seeded(seed+hashText(club.id)),used=new Set<string>(),arr:Player[]=[];
  for(let i=0;i<count;i++){const t=allTemplates[i%allTemplates.length];let p=makePlayer(t,`${club.id}_${i}_${seed}`,rnd,club,club.ovr,false);while(used.has(p.name))p=makePlayer(t,`${club.id}_${i}_${seed}_${used.size}`,rnd,club,club.ovr,false);used.add(p.name);p.transferListed=(i%5===0)||(p.age>=30&&i%3===0);p.scouted=i%11===0;arr.push(p)}
  return arr;
}
function generateOwnedSquad(seed:number){
  const club={id:USER_CLUB_ID,name:"Harbor City FC",country:"LEAGUE"},rnd=seeded(seed),used=new Set<string>(),templates=[...baseTemplates,...premiumTemplates.slice(0,4)];
  return templates.map((t,i)=>{let p=makePlayer(t,`own_${i}_${seed}`,rnd,club,68,true);while(used.has(p.name))p=makePlayer(t,`own_${i}_${seed}_${used.size}`,rnd,club,68,true);used.add(p.name);p.transferListed=false;return p});
}
function makeYouth(seed:number,index:number):Player{const rnd=seeded(seed+index*99991),t=allTemplates[index%allTemplates.length],club={id:USER_CLUB_ID,name:"Harbor City FC",country:"LEAGUE"},p=makePlayer(t,`y_${seed}_${index}`,rnd,club,64,true);p.age=17+Math.floor(rnd()*3);p.ovr=clamp(61+Math.floor(rnd()*9),61,69);p.pot=clamp(84+Math.floor(rnd()*8),84,92);p.contractYears=4;p.value=marketValue(p);p.wage=wageFor(p);p.desiredWage=Math.round(p.wage*1.08/10000)*10000;p.scouted=true;return p}
function buildFixtures(n:number){
  let order=Array.from({length:n},(_,i)=>i);const first:[number,number][][]=[];
  for(let r=0;r<n-1;r++){const pairs:[number,number][]=[];for(let i=0;i<n/2;i++){let a=order[i],b=order[n-1-i];if((r+i)%2===1)[a,b]=[b,a];pairs.push([a,b])}first.push(pairs);order=[order[0],order[n-1],...order.slice(1,n-1)]}
  return [...first,...first.map(round=>round.map(([a,b])=>[b,a] as [number,number]))];
}
const fixtures=buildFixtures(20);
function tableFresh():TableRow[]{return leagueClubs.map((c,i)=>({id:i,name:c.name,ovr:c.ovr,p:0,w:0,d:0,l:0,gf:0,ga:0,pts:0}))}
function allOpponentPlayers(state:any){return [...Object.values(state.rivalSquads||{}).flat() as Player[],...Object.values(state.worldSquads||{}).flat() as Player[]]}
function makeWorld(seed:number){const rivalSquads:any={},worldSquads:any={};for(const c of leagueClubs.slice(1))rivalSquads[c.id]=generateClubSquad(c,seed+7919,21);for(const c of foreignClubs)worldSquads[c.id]=generateClubSquad(c,seed+104729,20);return{rivalSquads,worldSquads}}
function resetSeasonStats(p:Player){p.apps=0;p.starts=0;p.goals=0;p.assists=0;p.mom=0;p.ratingTotal=0;p.avgRating=0;p.form=3;p.fit=92;p.injury=0}
function recalcPlayer(p:Player){p.value=marketValue(p);p.wage=Math.max(100000,p.wage||wageFor(p));p.desiredWage=Math.max(p.wage,Math.round((p.desiredWage||p.wage*1.08)/10000)*10000);p.form=clamp(p.form,1,5);p.fit=clamp(p.fit,20,100)}function fresh(){
  const seed=newSeed(),squad=generateOwnedSquad(seed),world=makeWorld(seed);
  return{version:5,seed,season:1,week:1,budget:5e8,fans:18000,squad,lineup:squad.slice(0,11).map(p=>p.id),bench:squad.slice(11,18).map(p=>p.id),formation:"433",facilities:{training:false,recovery:false,academy:false,stadium:false},table:tableFresh(),log:["20クラブ38試合制の新シーズンが開幕"],feed:[],lastNet:0,form:[],selectedPlayer:squad[9].id,match:null,history:[],complete:false,marketWindow:1,offers:[] as Offer[],negotiation:null as Negotiation|null,transferHistory:[] as any[],activeWorldClub:"1",marketCountry:"ALL",marketClub:"ALL",worldCountry:"LEAGUE",...world};
}
function normalizePlayer(p:any,owned=false):Player{
  const clubId=owned?USER_CLUB_ID:(p.clubId||"1"),club=clubId===USER_CLUB_ID?{name:"Harbor City FC",country:"LEAGUE"}:allClubs.find(c=>c.id===clubId)||{name:p.clubName||"Unknown FC",country:p.country||"LEAGUE"};
  const x:any={...p,clubId,clubName:p.clubName||club.name,country:p.country||club.country,contractYears:p.contractYears??(2+hashText(p.id||p.name)%4),desiredWage:p.desiredWage||Math.round((p.wage||wageFor(p))*1.1/10000)*10000,role:p.role||((p.ovr||65)>=78?"KEY":(p.ovr||65)>=72?"FIRST":"SQUAD"),transferListed:!!p.transferListed,ratingTotal:p.ratingTotal||0,avgRating:p.avgRating||0,scouted:owned?true:!!p.scouted};
  recalcPlayer(x);return x;
}
function migrateLegacy(old:any){
  const n=fresh();n.season=old.complete?(Number(old.season)||1)+1:Number(old.season)||1;n.budget=Number(old.budget)||n.budget;n.fans=Number(old.fans)||n.fans;n.facilities={...n.facilities,...(old.facilities||{})};n.history=Array.isArray(old.history)?old.history:[];
  if(Array.isArray(old.squad)&&old.squad.length){n.squad=old.squad.map((p:any)=>normalizePlayer(p,true));while(n.squad.length<22){const c={id:USER_CLUB_ID,name:"Harbor City FC",country:"LEAGUE"};n.squad.push(makePlayer(allTemplates[n.squad.length%allTemplates.length],`migrated_${n.seed}_${n.squad.length}`,seeded(n.seed+n.squad.length*19),c,66,true))}}
  n.lineup=n.squad.slice(0,11).map((p:Player)=>p.id);n.bench=n.squad.slice(11,18).map((p:Player)=>p.id);n.selectedPlayer=n.lineup[0];n.log.push("旧14試合セーブを移行：資金・所属選手・施設・履歴を引き継ぎ、38試合制を第1節から開始");return n;
}
function normalizeState(x:any){
  if(!x||x.version!==5)return null;x.squad=(x.squad||[]).map((p:any)=>normalizePlayer(p,true));for(const bag of [x.rivalSquads,x.worldSquads])for(const k of Object.keys(bag||{}))bag[k]=(bag[k]||[]).map((p:any)=>normalizePlayer(p,false));x.offers=x.offers||[];x.transferHistory=x.transferHistory||[];x.negotiation=x.negotiation||null;x.marketCountry=x.marketCountry||"ALL";x.marketClub=x.marketClub||"ALL";x.worldCountry=x.worldCountry||"LEAGUE";x.activeWorldClub=x.activeWorldClub||"1";return x;
}
function read(){try{const current=normalizeState(JSON.parse(localStorage.getItem(KEY)||"null"));if(current)return current;const legacy=JSON.parse(localStorage.getItem(LEGACY_KEY)||"null");return legacy?migrateLegacy(legacy):null}catch{return null}}
function save(x:any){try{localStorage.setItem(KEY,JSON.stringify(x))}catch{}}
function clear(){try{localStorage.removeItem(KEY);localStorage.removeItem(LEGACY_KEY)}catch{}}
function readBest(){try{return Number(localStorage.getItem(BEST)||0)||0}catch{return 0}}
function saveBest(n:number){if(n>readBest())try{localStorage.setItem(BEST,String(Math.round(n)))}catch{}}
let s:any=fresh();
function clubById(id:string){return allClubs.find(c=>c.id===id)||leagueClubs.find(c=>c.id===id)}
function squadForClub(id:string):Player[]{if(id===USER_CLUB_ID||id==="0")return s.squad;return (s.rivalSquads?.[id]||s.worldSquads?.[id]||[]) as Player[]}
function playerById(id:string):Player|undefined{return s.squad.find((p:Player)=>p.id===id)||allOpponentPlayers(s).find((p:Player)=>p.id===id)}
function removeFromSource(p:Player){if(s.rivalSquads?.[p.clubId])s.rivalSquads[p.clubId]=s.rivalSquads[p.clubId].filter((x:Player)=>x.id!==p.id);if(s.worldSquads?.[p.clubId])s.worldSquads[p.clubId]=s.worldSquads[p.clubId].filter((x:Player)=>x.id!==p.id)}
function addToClub(p:Player,clubId:string){const c=clubById(clubId);if(!c)return;p.clubId=c.id;p.clubName=c.name;p.country=c.country;p.transferListed=false;if(c.league)(s.rivalSquads[c.id]??=[]).push(p);else(s.worldSquads[c.id]??=[]).push(p)}function compatibility(p:Player,slot:string){if(p.pos.includes(slot))return 1;const sg=positionGroup(slot),groups=p.pos.map(positionGroup);if(sg==="GK"||groups.includes("GK"))return .48;if(groups.includes(sg))return .9;if((["LWB","RWB"].includes(slot)&&groups.includes("MF"))||(["LM","RM"].includes(slot)&&groups.includes("DF")))return .82;return .68}
function rawRoleRating(p:Player,slot:string){if(slot==="GK")return p.ovr;const g=positionGroup(slot);if(slot==="ST")return p.pac*.12+p.sho*.43+p.pas*.09+p.dri*.16+p.def*.02+p.phy*.18;if(["LW","RW"].includes(slot))return p.pac*.27+p.sho*.22+p.pas*.18+p.dri*.24+p.def*.02+p.phy*.07;if(slot==="AM")return p.pac*.13+p.sho*.18+p.pas*.31+p.dri*.28+p.def*.03+p.phy*.07;if(slot==="DM")return p.pac*.06+p.sho*.04+p.pas*.27+p.dri*.11+p.def*.33+p.phy*.19;if(["CM","LM","RM"].includes(slot))return p.pac*.11+p.sho*.1+p.pas*.32+p.dri*.21+p.def*.15+p.phy*.11;if(["LB","RB","LWB","RWB"].includes(slot))return p.pac*.18+p.sho*.03+p.pas*.17+p.dri*.11+p.def*.34+p.phy*.17;if(g==="DF")return p.pac*.06+p.sho*.01+p.pas*.08+p.dri*.03+p.def*.5+p.phy*.32;return p.ovr}
function slotRating(p:Player,slot:string){const form=.94+(p.form-1)*.03,fitness=.82+p.fit*.0018;return rawRoleRating(p,slot)*compatibility(p,slot)*form*fitness}
function slots(){return formations[s.formation] as [string,number,number][]}
function healthy(p:Player){return p.injury<=0}
function autoLineup(){const used=new Set<string>(),out:string[]=[];for(const [slot] of slots()){const candidates=[...s.squad].filter((p:Player)=>healthy(p)&&!used.has(p.id)).sort((a:Player,b:Player)=>slotRating(b,slot)-slotRating(a,slot));const pick=candidates[0]||s.squad.find((p:Player)=>!used.has(p.id));if(!pick)continue;out.push(pick.id);used.add(pick.id)}s.lineup=out;syncBench()}
function syncBench(){const valid=(s.bench||[]).filter((id:string)=>!s.lineup.includes(id)&&s.squad.some((p:Player)=>p.id===id));const rest=s.squad.filter((p:Player)=>!s.lineup.includes(p.id)&&!valid.includes(p.id)).sort((a:Player,b:Player)=>(healthy(b)?1:0)-(healthy(a)?1:0)||b.ovr-a.ovr).map((p:Player)=>p.id);s.bench=[...valid,...rest].slice(0,7)}
function lineStats(){let attack:number[]=[],mid:number[]=[],def:number[]=[],fit=0,form=0;slots().forEach(([slot],i)=>{const p=playerById(s.lineup[i]);if(!p)return;const r=slotRating(p,slot);fit+=compatibility(p,slot);form+=p.form;const g=positionGroup(slot);if(g==="FW")attack.push(r);else if(g==="MF")mid.push(r);else def.push(r)});const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:50,a=avg(attack),m=avg(mid),d=avg(def);return{attack:a*.8+m*.2,mid:m*.75+(a+d)*.125,def:d*.82+m*.18,ovr:(a+m+d)/3,fit:fit/11*100,fitness:s.lineup.reduce((x:number,id:string)=>x+(playerById(id)?.fit||70),0)/11,form:form/11}}
function sortedTable(){return[...s.table].sort((a:TableRow,b:TableRow)=>b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf)}
function applyResult(a:TableRow,b:TableRow,ga:number,gb:number){a.p++;b.p++;a.gf+=ga;a.ga+=gb;b.gf+=gb;b.ga+=ga;if(ga>gb){a.w++;b.l++;a.pts+=3}else if(ga<gb){b.w++;a.l++;b.pts+=3}else{a.d++;b.d++;a.pts++;b.pts++}}
function poisson(lambda:number){let L=Math.exp(-lambda),p=1,k=0;do{k++;p*=Math.random()}while(p>L&&k<9);return k-1}
function weighted<T>(arr:T[],weight:(x:T)=>number){let sum=arr.reduce((a,x)=>a+Math.max(.1,weight(x)),0),r=Math.random()*sum;for(const x of arr){r-=Math.max(.1,weight(x));if(r<=0)return x}return arr[arr.length-1]}
function develop(p:Player,xp:number){if(p.ovr>=p.pot)return;p.dev+=xp*(s.facilities.training?1.4:1)*(s.facilities.academy&&p.age<=23?1.25:1);while(p.dev>=100&&p.ovr<p.pot){p.dev-=100;p.ovr++;const attrs=["pac","sho","pas","dri","def","phy"];for(let i=0;i<3;i++){const k=attrs[ri(0,attrs.length-1)] as keyof Player;(p as any)[k]=clamp(Number((p as any)[k])+1,1,99)}recalcPlayer(p)}}
function payroll(){return s.squad.reduce((a:number,p:Player)=>a+p.wage,0)}
function currentFixture(){const round=fixtures[Math.min(s.week-1,TOTAL_MATCHES-1)]||fixtures[0],pair=round.find(([a,b])=>a===0||b===0)||[0,1];return{home:pair[0]===0,oppId:pair[0]===0?pair[1]:pair[0],round}}
function clubStrength(id:number){if(id===0)return lineStats().ovr;const roster=s.rivalSquads?.[String(id)]||[];if(!roster.length)return leagueClubs[id].ovr;return [...roster].sort((a:Player,b:Player)=>b.ovr-a.ovr).slice(0,11).reduce((x:number,p:Player)=>x+p.ovr,0)/11}
function updateRating(p:Player,rating:number){p.ratingTotal=(p.ratingTotal||0)+rating;p.avgRating=p.apps?Math.round(p.ratingTotal/p.apps*100)/100:0}function recordClubPlayerStats(clubId:number,goals:number,conceded:number){
  if(clubId===0)return;const roster=(s.rivalSquads?.[String(clubId)]||[]) as Player[];if(!roster.length)return;const starters=[...roster].sort((a,b)=>b.ovr-a.ovr).slice(0,11);for(const p of starters){p.apps++;p.starts++;p.fit=clamp(p.fit-ri(3,8),45,100);updateRating(p,6.15+(goals-conceded)*.08+(Math.random()-.5)*.7)}
  const outfield=starters.filter(p=>!p.pos.includes("GK"));for(let g=0;g<goals;g++){const scorer=weighted(outfield,p=>p.sho+p.pac*.15+(p.pos.includes("ST")?25:0));scorer.goals++;scorer.form=clamp(scorer.form+.16,1,5);updateRating(scorer,.65);const assists=outfield.filter(p=>p.id!==scorer.id);if(assists.length&&Math.random()<.8){const a=weighted(assists,p=>p.pas+p.dri*.25);a.assists++;updateRating(a,.35)}}
  const mom=[...starters].sort((a,b)=>b.avgRating-a.avgRating)[0];if(mom&&goals>=conceded)mom.mom++;
}
function simulateOtherLeagueFixtures(ourGoals:number,theirGoals:number){
  const fx=currentFixture(),opp=fx.oppId;recordClubPlayerStats(opp,theirGoals,ourGoals);for(const [a,b] of fx.round){if(a===0||b===0)continue;const sa=clubStrength(a),sb=clubStrength(b),ag=poisson(clamp(1.25+(sa-sb)/16,.25,3.2)),bg=poisson(clamp(1.1+(sb-sa)/16,.25,3));applyResult(s.table[a],s.table[b],ag,bg);recordClubPlayerStats(a,ag,bg);recordClubPlayerStats(b,bg,ag)}
}
function simulateWorldWeek(){
  for(const c of foreignClubs){const roster=(s.worldSquads?.[c.id]||[]) as Player[];if(!roster.length)continue;const starters=[...roster].sort((a,b)=>b.ovr-a.ovr).slice(0,11),goals=poisson(clamp(1.25+(c.ovr-72)/18,.5,2.8));for(const p of starters){p.apps++;p.starts++;updateRating(p,6.3+(Math.random()-.5)*.8)}const out=starters.filter(p=>!p.pos.includes("GK"));for(let g=0;g<goals;g++){const scorer=weighted(out,p=>p.sho+p.pac*.12+(p.pos.includes("ST")?20:0));scorer.goals++;updateRating(scorer,.6);const others=out.filter(p=>p.id!==scorer.id);if(others.length&&Math.random()<.78){const a=weighted(others,p=>p.pas+p.dri*.2);a.assists++;updateRating(a,.3)}}}
}
function applyTraining(){const tr=qs("[data-training]").value;for(const p of s.squad){if(p.injury>0)p.injury--;if(tr==="recovery")p.fit+=12;else if(tr==="fitness")p.fit+=7;else p.fit+=3;const ageBonus=p.age<=21?5:p.age<=24?3:1;develop(p,ageBonus+(tr==="balanced"?3:tr==="recovery"?0:4));if(tr==="attack"){p.sho=clamp(p.sho+.08,1,99);p.pas=clamp(p.pas+.05,1,99)}if(tr==="defense"){p.def=clamp(p.def+.08,1,99);p.phy=clamp(p.phy+.05,1,99)}recalcPlayer(p)}}
function tacticalNumbers(){const fx=currentFixture(),oppOvr=clubStrength(fx.oppId),ls=lineStats(),tactic=qs("[data-tactic]").value;let att=ls.attack,mid=ls.mid,def=ls.def,drain=8;const oppStyle=["balanced","press","counter","possession","block"][fx.oppId%5],edges:any={counter:{press:.8,possession:.3},possession:{block:.5,balanced:.2},press:{possession:.5,balanced:.15},block:{counter:.4,press:-.15},balanced:{}};const edge=edges[tactic]?.[oppStyle]??0;if(tactic==="press"){att+=1;mid+=.8;drain=12}else if(tactic==="counter"){att+=.5;def+=.35;drain=7}else if(tactic==="possession"){mid+=1;drain=9}else if(tactic==="block"){def+=1.1;att-=.35;drain=6}att+=edge;def+=edge*.6;return{att,mid,def,drain,oppOvr,ls}}
function recordGoal(minute:number){const outfield:Player[]=(s.lineup as string[]).map((id:string)=>playerById(id)).filter((p:Player|undefined):p is Player=>!!p&&!p.pos.includes("GK"));const scorer=weighted<Player>(outfield,(p:Player)=>p.sho+p.pac*.18+p.form*7+(p.pos.includes("ST")?25:0));const others:Player[]=outfield.filter((p:Player)=>p.id!==scorer.id);const assist=Math.random()<.82&&others.length?weighted<Player>(others,(p:Player)=>p.pas+p.dri*.35):null;scorer.goals++;scorer.form=clamp(scorer.form+.22,1,5);s.match.contrib[scorer.id]=(s.match.contrib[scorer.id]||0)+3;if(assist){assist.assists++;assist.form=clamp(assist.form+.12,1,5);s.match.contrib[assist.id]=(s.match.contrib[assist.id]||0)+2}s.feed.push(`<b>${minute}'</b> ⚽ ${esc(scorer.name)}${assist?"（A: "+esc(assist.name)+"）":""}`)}
function simulateHalf(half:number){const n=tacticalNumbers(),condition=(n.ls.fitness-70)*.025+(n.ls.form-3)*.38,ourXg=clamp((1.18+(n.att*.55+n.mid*.22+condition-n.oppOvr*.75)/13)/2,.08,1.9),theirXg=clamp((1.08+(n.oppOvr*.78-(n.def*.58+n.mid*.18+condition))/14)/2,.08,1.8),goals=poisson(ourXg),oppGoals=poisson(theirXg),start=half===1?5:50,end=half===1?44:89;for(let i=0;i<goals;i++)recordGoal(ri(start,end));const opp=leagueClubs[currentFixture().oppId];for(let i=0;i<oppGoals;i++)s.feed.push(`<b>${ri(start,end)}'</b> ⚠️ ${esc(opp.name)} が得点`);s.match.our+=goals;s.match.their+=oppGoals;for(const id of s.lineup){const p=playerById(id);if(p){p.fit-=n.drain/2;recalcPlayer(p)}}return{ourXg,theirXg}}
function initMatch(){const injured=s.lineup.map((id:string)=>playerById(id)).filter((p:Player|undefined)=>p&&p.injury>0);if(injured.length){q("[data-result]").textContent="負傷中の選手がスタメンです。ベストXI自動選出か手動変更をしてください。";return false}applyTraining();const participants=[...s.lineup];for(const id of participants){const p=playerById(id);if(p){p.apps++;p.starts++}}s.match={phase:"first",our:0,their:0,usedSubs:0,participants,contrib:{},xgFor:0,xgAgainst:0};s.feed=[`<b>0'</b> KICK OFF　${s.formation} / ${esc(qs("[data-tactic]").selectedOptions[0]?.textContent||"")}`];return true}function kickoff(){if(!initMatch())return;const x=simulateHalf(1);s.match.xgFor+=x.ourXg;s.match.xgAgainst+=x.theirXg;s.match.phase="halftime";const opp=leagueClubs[currentFixture().oppId];s.feed.push(`<b>45'</b> HALF TIME　Harbor City ${s.match.our} - ${s.match.their} ${esc(opp.name)}`);q("[data-scoreline]").textContent=s.match.our+" - "+s.match.their;q("[data-result]").textContent=`HALF TIME ${s.match.our} - ${s.match.their}｜交代・戦術変更ができます。`;save(s);render();requestAnimationFrame(()=>q("[data-halftime]").scrollIntoView({block:"center"}))}
function makeSub(){if(!s.match||s.match.phase!=="halftime"||s.match.usedSubs>=3)return;const outId=qs("[data-sub-out]").value,inId=qs("[data-sub-in]").value,li=s.lineup.indexOf(outId),bi=s.bench.indexOf(inId);if(li<0||bi<0)return;const incoming=playerById(inId);if(!incoming||!healthy(incoming))return;s.lineup[li]=inId;s.bench[bi]=outId;s.match.usedSubs++;if(!s.match.participants.includes(inId)){s.match.participants.push(inId);incoming.apps++}s.feed.push(`<b>HT</b> 🔄 ${esc(playerById(outId)?.name)} → ${esc(incoming.name)}`);save(s);render()}
function finalizeMatch(){
  const our=s.match.our,their=s.match.their,fx=currentFixture(),opp=s.table[fx.oppId];applyResult(s.table[0],opp,our,their);simulateOtherLeagueFixtures(our,their);simulateWorldWeek();const won=our>their,draw=our===their,res=won?"W":draw?"D":"L";s.form.push(res);if(s.form.length>5)s.form.shift();
  for(const id of s.match.participants){const p=playerById(id);if(!p)continue;p.form=clamp(p.form+(won?.12:draw?.03:-.1),1,5);develop(p,8+(p.age<=23?5:0)+(s.match.contrib[id]||0)*3);updateRating(p,6.25+(won?.25:draw?.05:-.18)+(s.match.contrib[id]||0)*.32+(Math.random()-.5)*.5);recalcPlayer(p)}
  const momId=[...s.match.participants].sort((a,b)=>(s.match.contrib[b]||0)-(s.match.contrib[a]||0)||(playerById(b)?.avgRating||0)-(playerById(a)?.avgRating||0))[0],mom=playerById(momId);if(mom){mom.mom++;mom.form=clamp(mom.form+.15,1,5)}
  const attendance=Math.round(s.fans*(fx.home?(.76+Math.random()*.2):.22)),income=Math.round(attendance*(s.facilities.stadium?4200:3200)+(won?1.4e7:draw?7e6:3e6)),pay=payroll(),net=income-pay;s.lastNet=net;s.budget+=net;s.fans=clamp(s.fans+(won?ri(700,1700):draw?ri(100,500):-ri(100,600)),7000,80000);for(const p of s.squad)p.fit+=s.facilities.recovery?6:2;
  const lowFit=s.lineup.map((id:string)=>playerById(id)).filter((p:Player|undefined):p is Player=>!!p&&p.fit<62&&p.injury===0);if(lowFit.length&&Math.random()<.16){const injured=lowFit[ri(0,lowFit.length-1)];injured.injury=ri(1,3);s.feed.push(`<b>90'</b> 🚑 ${esc(injured.name)} が負傷。離脱 ${injured.injury}節`)}
  const oppClub=leagueClubs[fx.oppId];s.feed.push(`<b>90'</b> FULL TIME　Harbor City ${our} - ${their} ${esc(oppClub.name)}`);if(mom)s.feed.push(`⭐ MOM: ${esc(mom.name)}`);q("[data-scoreline]").textContent=our+" - "+their;s.log.push(`S${s.season} 第${s.week}節 ${res} ${our}-${their} vs ${oppClub.name} / 収支 ${net>=0?"+":""}${yen(net)}`);q("[data-result]").textContent=`${our} - ${their}　${won?"WIN":draw?"DRAW":"LOSE"}｜xG ${s.match.xgFor.toFixed(1)}-${s.match.xgAgainst.toFixed(1)}${mom?"｜MOM "+mom.name:""}`;
  s.match=null;s.week++;if([7,20,25].includes(s.week))s.log.push(s.week===20?"WINTER WINDOW OPEN：移籍交渉を再開できます":s.week===25?"WINTER WINDOW CLOSED":"SUMMER WINDOW CLOSED");maybeGenerateIncomingOffer();if(s.week>TOTAL_MATCHES)finishSeason();else{save(s);render()}
}
function finishMatch(){const x=simulateHalf(2);s.match.xgFor+=x.ourXg;s.match.xgAgainst+=x.theirXg;finalizeMatch()}
function quickMatch(){if(s.complete||s.match)return;if(s.lineup.some((id:string)=>(playerById(id)?.injury||0)>0))autoLineup();if(!initMatch())return;const a=simulateHalf(1),b=simulateHalf(2);s.match.xgFor=a.ourXg+b.ourXg;s.match.xgAgainst=a.theirXg+b.theirXg;finalizeMatch()}
function transferWindowOpen(){return !s.complete&&(s.week<=6||(s.week>=20&&s.week<=24))}
function askingPrice(p:Player){const premium=p.transferListed?.98:1.12,ageAdj=p.age<=21?1.08:p.age>=31?.94:1;return Math.round(p.value*premium*ageAdj/1000000)*1000000}
function desiredYears(p:Player){return p.age<=23?4:p.age>=31?2:3}
function marketGroup(p:Player){const gs=new Set(p.pos.map(positionGroup));if(gs.has("GK"))return"GK";if(gs.has("DF"))return"DF";if(gs.has("MF"))return"MF";return"FW"}
function marketPool(){const country=s.marketCountry||"ALL",club=s.marketClub||"ALL",filter=qs("[data-market-filter]").value,sort=qs("[data-market-sort]").value;let arr=allOpponentPlayers(s).filter((p:Player)=>(club!=="ALL"?p.clubId===club:(country==="ALL"?p.transferListed:p.country===country&&p.transferListed))&&(filter==="ALL"||marketGroup(p)===filter));arr=[...arr].sort((a,b)=>sort==="price"?a.value-b.value:sort==="age"?a.age-b.age:sort==="pot"?b.pot-a.pot:b.ovr-a.ovr);return arr.slice(0,48)}function startTransferNegotiation(id:string){const p=playerById(id);if(!p||s.squad.some((x:Player)=>x.id===id))return;if(!transferWindowOpen()){q("[data-result]").textContent="現在は移籍期間外です。夏は第1〜6節、冬は第20〜24節に交渉できます。";return}const ask=askingPrice(p);s.negotiation={playerId:id,phase:"club",offer:Math.round(ask*.9/1000000)*1000000,ask,fee:0,wage:p.desiredWage,years:desiredYears(p),rounds:0,renewal:false,message:`${p.clubName} は ${yen(ask)} 前後を希望しています。`};p.scouted=true;s.selectedPlayer=id;save(s);renderNegotiation();playerProfile(p)}
function startRenewal(id:string){const p=s.squad.find((x:Player)=>x.id===id);if(!p)return;s.negotiation={playerId:id,phase:"contract",offer:0,ask:0,fee:0,wage:Math.max(p.wage,Math.round(p.desiredWage*.96/10000)*10000),years:desiredYears(p),rounds:0,renewal:true,message:`${p.name} と契約更新交渉。希望年俸は ${yen(p.desiredWage)} / 節です。`};activateTab("market");renderNegotiation()}
function submitClubOffer(){const n=s.negotiation as Negotiation|null;if(!n||n.phase!=="club")return;const p=playerById(n.playerId);if(!p)return;const min=Math.round(n.ask*(p.transferListed?.94:1.02)/1000000)*1000000;if(n.offer>=min){n.phase="contract";n.fee=n.offer;n.wage=p.desiredWage;n.years=desiredYears(p);n.message=`${p.clubName} が ${yen(n.fee)} で合意。次は選手本人と契約条件を交渉します。`}else{n.rounds++;if(n.rounds>=3){n.message=`${p.clubName} が交渉を打ち切りました。`;setTimeout(()=>{s.negotiation=null;save(s);renderNegotiation()},700)}else{n.ask=Math.round(Math.max(n.offer*1.08,n.ask*(.96-.01*n.rounds))/1000000)*1000000;n.offer=Math.round((n.offer+n.ask)/2/1000000)*1000000;n.message=`提示額が低すぎます。クラブ側の新しい要求は ${yen(n.ask)}。`}}save(s);renderNegotiation()}
function submitContractOffer(){const n=s.negotiation as Negotiation|null;if(!n||n.phase!=="contract")return;const p=playerById(n.playerId);if(!p)return;const wageTarget=p.desiredWage*(n.renewal?.98:1),yearsTarget=desiredYears(p);if(n.wage>=wageTarget*.97&&n.years>=Math.max(1,yearsTarget-1)){if(n.renewal){p.wage=n.wage;p.contractYears=n.years;p.desiredWage=Math.round(n.wage*1.1/10000)*10000;s.log.push(`契約更新：${p.name} ${n.years}年 / ${yen(n.wage)} per match`);s.transferHistory.push({season:s.season,week:s.week,type:"RENEW",player:p.name,club:"Harbor City FC",fee:0})}else{if(!completeSigning(p,n)){save(s);return}}s.negotiation=null;save(s);render()}else{n.rounds++;p.desiredWage=Math.round(p.desiredWage*(1-.015*Math.min(n.rounds,2))/10000)*10000;n.wage=p.desiredWage;n.years=Math.max(n.years,yearsTarget);n.message=`選手側がカウンター。年俸 ${yen(p.desiredWage)} / 節、${yearsTarget}年以上を希望。`;save(s);renderNegotiation()}}
function completeSigning(p:Player,n:Negotiation){if(s.budget<n.fee){n.message="移籍金を支払う予算がありません。";renderNegotiation();return false}s.budget-=n.fee;const from=p.clubName;removeFromSource(p);p.clubId=USER_CLUB_ID;p.clubName="Harbor City FC";p.country="LEAGUE";p.wage=n.wage;p.contractYears=n.years;p.desiredWage=Math.round(n.wage*1.1/10000)*10000;p.transferListed=false;p.scouted=true;p.price=0;s.squad.push(p);s.selectedPlayer=p.id;s.log.push(`獲得：${p.name} / ${from} / ${yen(n.fee)} / ${n.years}年契約`);s.transferHistory.push({season:s.season,week:s.week,type:"IN",player:p.name,club:from,fee:n.fee});syncBench();return true}
function cancelNegotiation(){s.negotiation=null;save(s);renderNegotiation()}
function refreshMarket(){if(s.budget<5e6||s.match)return;s.budget-=5e6;s.marketWindow=(s.marketWindow||1)+1;for(const c of allClubs){const roster=squadForClub(c.id);if(!roster.length)continue;const rnd=seeded(s.seed+s.season*991+s.marketWindow*7919+hashText(c.id));for(const p of roster)p.transferListed=rnd()<.23||(p.age>=30&&rnd()<.35)}s.log.push(`スカウト網更新：移籍候補 WINDOW ${s.marketWindow}`);save(s);render()}
function maybeGenerateIncomingOffer(){if(!transferWindowOpen()||![3,5,20,22,24].includes(s.week)||s.squad.length<=18)return;const pending=(s.offers as Offer[]).some(o=>o.status==="pending");if(pending)return;const candidates=[...s.squad].filter((p:Player)=>!p.injury).sort((a:Player,b:Player)=>(b.transferListed?1:0)-(a.transferListed?1:0)||b.value-a.value);const p=candidates[(s.week+s.season)%Math.min(8,candidates.length)],buyers=foreignClubs.filter(c=>c.ovr>=Math.max(68,p.ovr-5)),buyer=buyers[(hashText(p.id)+s.week)%buyers.length]||foreignClubs[0],mult=.88+((hashText(p.id+buyer.id+s.week)%31)/100),amount=Math.round(p.value*mult/1000000)*1000000;const offer:Offer={id:`of_${s.season}_${s.week}_${p.id}`,playerId:p.id,clubId:buyer.id,clubName:buyer.name,amount,countered:false,final:false,status:"pending"};s.offers.push(offer);s.log.push(`移籍オファー：${buyer.name} → ${p.name} ${yen(amount)}`)}
function moveSoldPlayer(p:Player,buyerId:string,fee:number){s.budget+=fee;s.squad=s.squad.filter((x:Player)=>x.id!==p.id);s.lineup=s.lineup.filter((x:string)=>x!==p.id);s.bench=s.bench.filter((x:string)=>x!==p.id);addToClub(p,buyerId);s.transferHistory.push({season:s.season,week:s.week,type:"OUT",player:p.name,club:p.clubName,fee});while(s.squad.length<18)s.squad.push(makeYouth(s.seed+s.season*999,s.squad.length));autoLineup();s.selectedPlayer=s.lineup[0]}
function acceptIncomingOffer(id:string){const o=(s.offers as Offer[]).find(x=>x.id===id),p=o&&s.squad.find((x:Player)=>x.id===o.playerId);if(!o||!p||o.status!=="pending")return;moveSoldPlayer(p,o.clubId,o.amount);o.status="accepted";s.log.push(`売却成立：${p.name} → ${o.clubName} ${yen(o.amount)}`);save(s);render()}
function rejectIncomingOffer(id:string){const o=(s.offers as Offer[]).find(x=>x.id===id);if(!o||o.status!=="pending")return;o.status="rejected";s.log.push(`移籍オファー拒否：${o.clubName}`);save(s);render()}
function counterIncomingOffer(id:string){const o=(s.offers as Offer[]).find(x=>x.id===id),p=o&&s.squad.find((x:Player)=>x.id===o.playerId);if(!o||!p||o.status!=="pending")return;const demand=Math.round(o.amount*1.15/1000000)*1000000,max=Math.round(p.value*(1.03+(hashText(o.clubId+p.id)%18)/100)/1000000)*1000000;o.countered=true;if(demand<=max){o.amount=demand;moveSoldPlayer(p,o.clubId,demand);o.status="accepted";s.log.push(`カウンター成功：${p.name} ${yen(demand)}で売却`)}else{o.amount=max;o.final=true;s.log.push(`${o.clubName} が最終提示 ${yen(max)}`)}save(s);render()}
function toggleTransferList(id:string){const p=s.squad.find((x:Player)=>x.id===id);if(!p)return;p.transferListed=!p.transferListed;s.log.push(`${p.name} を移籍リスト${p.transferListed?"に登録":"から解除"}`);save(s);render()}function scoutPlayer(id:string){const p=playerById(id);if(!p||p.scouted||s.budget<2e6)return;s.budget-=2e6;p.scouted=true;s.selectedPlayer=id;s.log.push("スカウト完了："+p.name);save(s);render()}
function renderPitch(){q("[data-pitch-lineup]").innerHTML=slots().map(([slot,x,y],i)=>{const p=playerById(s.lineup[i]);if(!p)return"";const fit=Math.round(compatibility(p,slot)*100);return`<button class="pitch-lineup-player ${fit<90?"out-position":""}" type="button" style="left:${x}%;top:${y}%" data-profile="${p.id}" title="${esc(p.name)} / 適性 ${fit}%"><span>${slot}</span><b>${esc(p.name.split(" ").slice(-1)[0])}</b><small>${Math.round(slotRating(p,slot))}・${Math.round(p.fit)}%</small></button>`}).join("")}
function renderLineupEditor(){q("[data-lineup-editor]").innerHTML=slots().map(([slot],i)=>{const current=s.lineup[i],opts=[...s.squad].sort((a:Player,b:Player)=>slotRating(b,slot)-slotRating(a,slot)).map((p:Player)=>`<option value="${p.id}" ${p.id===current?"selected":""} ${p.injury>0?"disabled":""}>${esc(p.name)}｜${p.pos.join("/")}｜${Math.round(slotRating(p,slot))}${p.injury>0?" 🚑":""}</option>`).join(""),cp=playerById(current),fit=cp?Math.round(compatibility(cp,slot)*100):0;return`<div class="lineup-row"><b>${slot}</b><select data-lineup-slot="${i}" ${s.match?"disabled":""}>${opts}</select><span class="${fit<90?"bad-fit":"good-fit"}">${fit}%</span></div>`}).join("");root.querySelectorAll<HTMLSelectElement>("[data-lineup-slot]").forEach(el=>el.onchange=()=>{const i=Number(el.dataset.lineupSlot),old=s.lineup[i],next=el.value,other=s.lineup.indexOf(next),benchI=s.bench.indexOf(next);if(other>=0&&other!==i)s.lineup[other]=old;else if(benchI>=0)s.bench[benchI]=old;s.lineup[i]=next;s.selectedPlayer=next;syncBench();save(s);render()})}
function renderBench(){syncBench();q("[data-bench-editor]").innerHTML=s.bench.map((id:string,i:number)=>{const p=playerById(id);if(!p)return"";const available=s.squad.filter((x:Player)=>!s.lineup.includes(x.id)&&(x.id===id||!s.bench.includes(x.id))),opts=[p,...available.filter((x:Player)=>x.id!==id)].sort((a:Player,b:Player)=>b.ovr-a.ovr).map((x:Player)=>`<option value="${x.id}" ${x.id===id?"selected":""}>${esc(x.name)}｜${x.ovr}${x.injury>0?" 🚑":""}</option>`).join("");return`<div class="bench-row"><span>${i+1}</span><select data-bench-slot="${i}" ${s.match?"disabled":""}>${opts}</select><b>${p.pos[0]}</b></div>`}).join("");root.querySelectorAll<HTMLSelectElement>("[data-bench-slot]").forEach(el=>el.onchange=()=>{const i=Number(el.dataset.benchSlot),next=el.value,other=s.bench.indexOf(next),old=s.bench[i];if(other>=0)s.bench[other]=old;s.bench[i]=next;save(s);render()})}
function renderSquad(){q("[data-squad-count]").textContent=s.squad.length+" players";q("[data-squad-table]").innerHTML=[...s.squad].sort((a:Player,b:Player)=>b.ovr-a.ovr).map((p:Player)=>`<tr class="${p.injury>0?"injured-row":""}"><td><button type="button" class="player-name-button" data-profile="${p.id}">${p.nation} ${esc(p.name)}</button></td><td>${p.pos.join("/")}</td><td>${p.age}</td><td><b>${p.ovr}</b></td><td class="pot-cell">${p.pot}</td><td>${p.form.toFixed(1)} ${formText(p)}</td><td>${Math.round(p.fit)}%</td><td>${p.apps}</td><td>${p.goals}</td><td>${p.assists}</td><td>${p.avgRating?p.avgRating.toFixed(2):"--"}</td><td>${yen(p.value)}</td><td>${p.contractYears}年</td><td>${s.lineup.includes(p.id)?"<span class='starting-badge'>XI</span>":p.transferListed?"<span class='transfer-badge'>LIST</span>":s.bench.includes(p.id)?"<span class='bench-badge'>SUB</span>":""}</td></tr>`).join("");bindProfileButtons()}
function bindProfileButtons(){root.querySelectorAll<HTMLButtonElement>("[data-profile]").forEach(b=>b.onclick=()=>{const p=playerById(b.dataset.profile!);if(!p)return;s.selectedPlayer=p.id;playerProfile(p);save(s)})}
function renderHalftime(){const box=q("[data-halftime]");if(!s.match||s.match.phase!=="halftime"){box.hidden=true;return}box.hidden=false;q("[data-halftime-score]").textContent=s.match.our+" - "+s.match.their;q("[data-sub-count]").textContent="交代 "+s.match.usedSubs+" / 3";const out=qs("[data-sub-out]"),inn=qs("[data-sub-in]");out.innerHTML=s.lineup.map((id:string)=>{const p=playerById(id);return p?`<option value="${id}">${esc(p.name)}｜FIT ${Math.round(p.fit)}</option>`:""}).join("");inn.innerHTML=s.bench.filter((id:string)=>{const p=playerById(id);return p&&healthy(p)}).map((id:string)=>{const p=playerById(id)!;return`<option value="${id}">${esc(p.name)}｜${p.pos.join("/")}｜FIT ${Math.round(p.fit)}</option>`}).join("");qb("[data-make-sub]").disabled=s.match.usedSubs>=3||!inn.options.length}
function optionLabelCountry(c:string){return c==="LEAGUE"?"国内リーグ":c}
function clubsForCountry(country:string){return country==="ALL"?allClubs:country==="LEAGUE"?leagueClubs.slice(1):foreignClubs.filter(c=>c.country===country)}function syncMarketFilters(){const country=qs("[data-market-country]"),club=qs("[data-market-club]");if(!country.options.length)country.innerHTML=`<option value="ALL">ALL COUNTRIES</option>`+countries.map(c=>`<option value="${c}">${optionLabelCountry(c)}</option>`).join("");country.value=s.marketCountry||"ALL";const clubs=clubsForCountry(country.value);club.innerHTML=`<option value="ALL">ALL CLUBS</option>`+clubs.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("");if(!clubs.some(c=>c.id===s.marketClub))s.marketClub="ALL";club.value=s.marketClub}
function renderMarket(){syncMarketFilters();const list=marketPool(),open=transferWindowOpen();q("[data-window-status]").textContent=open?"WINDOW OPEN":"WINDOW CLOSED";q("[data-window-status]").className=open?"open":"closed";q("[data-market-count]").textContent=list.length+" players";q("[data-market-window]").textContent=open?(s.week<=6?"SUMMER WINDOW OPEN":"WINTER WINDOW OPEN"):(s.week<20?"NEXT: WINTER WINDOW / 第20節":"NEXT: SUMMER / 来季");q("[data-transfer-market]").innerHTML=list.map((p:Player)=>{const known=p.scouted,tag=p.transferListed?"LISTED":p.age<=20&&p.pot>=86?"WONDERKID":p.ovr>=79?"STAR":p.trait;return`<article class="market-player-card ${known?"scouted":""}"><button class="market-profile-open" type="button" data-profile="${p.id}"><span>${p.nation}</span><div><strong>${esc(p.name)}</strong><small>${esc(p.country)} / ${esc(p.clubName)}<br>${p.pos.join(" / ")} ・ ${p.age}歳</small></div><em>${p.ovr}<small>OVR</small></em></button><div class="market-tag-row"><span>${tag}</span><b>${yen(p.value)}</b></div><div class="market-mini-stats"><span>APP <b>${p.apps}</b></span><span>G <b>${p.goals}</b></span><span>A <b>${p.assists}</b></span><span>AVG <b>${p.avgRating?p.avgRating.toFixed(2):"--"}</b></span><span>POT <b>${known?p.pot:"??"}</b></span><span>CON <b>${p.contractYears}y</b></span></div><div class="market-card-actions"><button class="market-scout" type="button" data-scout-player="${p.id}" ${known||s.budget<2e6?"disabled":""}>${known?"SCOUTED":"スカウト ¥2,000,000"}</button><button class="market-buy" type="button" data-buy-player="${p.id}" ${!open?"disabled":""}>交渉する</button></div></article>`}).join("")||`<div class="empty-state">条件に合う移籍候補がいません。クラブ指定か市場更新を試してください。</div>`;root.querySelectorAll<HTMLButtonElement>("[data-buy-player]").forEach(b=>b.onclick=()=>startTransferNegotiation(b.dataset.buyPlayer!));root.querySelectorAll<HTMLButtonElement>("[data-scout-player]").forEach(b=>b.onclick=()=>scoutPlayer(b.dataset.scoutPlayer!));bindProfileButtons();renderNegotiation()}
function renderNegotiation(){const box=q("[data-negotiation]");const n=s.negotiation as Negotiation|null;if(!n){box.hidden=true;box.innerHTML="";return}const p=playerById(n.playerId);if(!p){box.hidden=true;return}box.hidden=false;if(n.phase==="club"){box.innerHTML=`<div class="negotiation-head"><div><span>CLUB NEGOTIATION</span><strong>${esc(p.name)} / ${esc(p.clubName)}</strong></div><button type="button" data-cancel-negotiation>×</button></div><p>${esc(n.message)}</p><div class="negotiation-grid"><label>あなたの提示額<input data-negotiation-fee type="number" min="1000000" step="1000000" value="${n.offer}"></label><div><span>市場価値</span><b>${yen(p.value)}</b></div><div><span>相手要求</span><b>${yen(n.ask)}</b></div></div><button class="sim-primary" type="button" data-submit-club-offer>移籍金を提示</button>`}else{box.innerHTML=`<div class="negotiation-head"><div><span>${n.renewal?"CONTRACT RENEWAL":"PLAYER CONTRACT"}</span><strong>${esc(p.name)}</strong></div><button type="button" data-cancel-negotiation>×</button></div><p>${esc(n.message)}</p><div class="negotiation-grid"><label>年俸相当 / 節<input data-negotiation-wage type="number" min="100000" step="10000" value="${n.wage}"></label><label>契約年数<select data-negotiation-years>${[1,2,3,4,5].map(y=>`<option value="${y}" ${y===n.years?"selected":""}>${y}年</option>`).join("")}</select></label><div><span>現在契約</span><b>${p.contractYears}年 / ${yen(p.wage)}</b></div></div><button class="sim-primary" type="button" data-submit-contract-offer>${n.renewal?"更新条件を提示":"選手へ契約条件を提示"}</button>`}box.querySelector<HTMLButtonElement>("[data-cancel-negotiation]")!.onclick=cancelNegotiation;const fee=box.querySelector<HTMLInputElement>("[data-negotiation-fee]");if(fee)fee.onchange=()=>n.offer=Math.max(1e6,Number(fee.value)||1e6);const wage=box.querySelector<HTMLInputElement>("[data-negotiation-wage]");if(wage)wage.onchange=()=>n.wage=Math.max(100000,Number(wage.value)||100000);const years=box.querySelector<HTMLSelectElement>("[data-negotiation-years]");if(years)years.onchange=()=>n.years=Number(years.value);box.querySelector<HTMLButtonElement>("[data-submit-club-offer]")?.addEventListener("click",submitClubOffer);box.querySelector<HTMLButtonElement>("[data-submit-contract-offer]")?.addEventListener("click",submitContractOffer)}function syncWorldFilters(){const country=qs("[data-world-country]"),club=qs("[data-world-club]");if(!country.options.length)country.innerHTML=countries.map(c=>`<option value="${c}">${optionLabelCountry(c)}</option>`).join("");country.value=s.worldCountry||"LEAGUE";const clubs=clubsForCountry(country.value);club.innerHTML=clubs.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("");if(!clubs.some(c=>c.id===s.activeWorldClub))s.activeWorldClub=clubs[0]?.id||"1";club.value=s.activeWorldClub}
function renderWorld(){syncWorldFilters();const club=clubById(s.activeWorldClub),roster=squadForClub(s.activeWorldClub);if(!club){q("[data-world-roster]").innerHTML="";return}q("[data-world-club-summary]").textContent=`${club.flag} ${club.name} / OVR ${club.ovr}`;q("[data-world-roster]").innerHTML=[...roster].sort((a,b)=>b.ovr-a.ovr).map(p=>`<tr><td><button type="button" class="player-name-button" data-profile="${p.id}">${p.nation} ${esc(p.name)}</button></td><td>${p.pos.join("/")}</td><td>${p.age}</td><td><b>${p.ovr}</b></td><td>${p.scouted?p.pot:"??"}</td><td>${p.apps}</td><td>${p.goals}</td><td>${p.assists}</td><td>${p.avgRating?p.avgRating.toFixed(2):"--"}</td><td>${p.contractYears}年</td><td>${yen(p.value)}</td><td><button class="table-action" type="button" data-db-negotiate="${p.id}" ${!transferWindowOpen()?"disabled":""}>交渉</button></td></tr>`).join("");root.querySelectorAll<HTMLButtonElement>("[data-db-negotiate]").forEach(b=>b.onclick=()=>{activateTab("market");s.marketCountry=club.country;s.marketClub=club.id;startTransferNegotiation(b.dataset.dbNegotiate!)});bindProfileButtons()}
function renderOffers(){const pending=(s.offers as Offer[]).filter(o=>o.status==="pending"),box=q("[data-transfer-offers]");q("[data-offer-count]").textContent=pending.length+" pending";box.innerHTML=pending.length?pending.map(o=>{const p=s.squad.find((x:Player)=>x.id===o.playerId);return p?`<article class="offer-card"><div><span>${esc(o.clubName)}</span><strong>${esc(p.name)}</strong><small>市場価値 ${yen(p.value)} / 提示 ${yen(o.amount)}${o.final?" / FINAL":""}</small></div><div class="offer-actions"><button type="button" data-offer-reject="${o.id}">拒否</button><button type="button" data-offer-counter="${o.id}" ${o.final?"disabled":""}>+15% カウンター</button><button type="button" data-offer-accept="${o.id}">承諾</button></div></article>`:""}).join(""):`<p>現在オファーはありません。移籍期間中は所属選手へのオファーが届くことがあります。</p>`;root.querySelectorAll<HTMLButtonElement>("[data-offer-accept]").forEach(b=>b.onclick=()=>acceptIncomingOffer(b.dataset.offerAccept!));root.querySelectorAll<HTMLButtonElement>("[data-offer-reject]").forEach(b=>b.onclick=()=>rejectIncomingOffer(b.dataset.offerReject!));root.querySelectorAll<HTMLButtonElement>("[data-offer-counter]").forEach(b=>b.onclick=()=>counterIncomingOffer(b.dataset.offerCounter!))}
function renderLeaders(){const leaguePlayers=[...s.squad,...Object.values(s.rivalSquads||{}).flat() as Player[]].sort((a,b)=>b.goals-a.goals||b.assists-a.assists||b.avgRating-a.avgRating).slice(0,8);q("[data-player-leaders]").innerHTML=leaguePlayers.map((p,i)=>`<button type="button" data-profile="${p.id}"><span>${i+1}</span><b>${esc(p.name)}<small>${esc(p.clubName)}</small></b><small>${p.goals}G / ${p.assists}A / AVG ${p.avgRating?p.avgRating.toFixed(2):"--"}</small></button>`).join("");bindProfileButtons()}
function renderTransferHistory(){q("[data-transfer-history-count]").textContent=s.transferHistory.length+" deals";q("[data-transfer-history]").innerHTML=s.transferHistory.length?s.transferHistory.slice(-12).reverse().map((h:any)=>`<div><b>${h.type}</b><span>${esc(h.player)}</span><span>${esc(h.club)}</span><strong>${h.fee?yen(h.fee):"契約更新"}</strong><small>S${h.season} / W${h.week}</small></div>`).join(""):`<p>まだ移籍はありません。</p>`}
function renderHistory(){q("[data-history-count]").textContent=s.history.length+" seasons";q("[data-season-history]").innerHTML=s.history.length?s.history.slice().reverse().map((h:any)=>`<div><b>S${h.season}</b><span>${h.rank}位</span><span>${h.points}pt</span><span>${h.record}</span><span>賞金 ${yen(h.prize)}</span></div>`).join(""):`<p>まだ完了したシーズンはありません。</p>`}function applyOffseasonDevelopment(p:Player,owned:boolean){
  const priorAge=p.age,apps=p.apps,avg=p.avgRating||0;p.age++;
  let growth=0;if(priorAge<=20)growth=48+Math.min(26,apps)+((owned&&s.facilities.academy)?22:0);else if(priorAge<=23)growth=30+Math.min(22,apps*.7)+((owned&&s.facilities.training)?15:0);else if(priorAge<=29&&avg>=7&&p.ovr<p.pot)growth=18+Math.min(15,apps*.35);
  if(growth>0){p.dev+=growth;while(p.dev>=100&&p.ovr<p.pot){p.dev-=100;p.ovr++;for(const k of ["pac","sho","pas","dri","def","phy"].sort(()=>Math.random()-.5).slice(0,3) as (keyof Player)[])(p as any)[k]=clamp(Number((p as any)[k])+1,1,99)}}
  let decline=0;if(priorAge>=36)decline=Math.random()<.75?1:0;else if(priorAge>=34)decline=Math.random()<.45?1:0;else if(priorAge>=32&&avg>0&&avg<6.25)decline=Math.random()<.22?1:0;
  if(decline){p.ovr=clamp(p.ovr-decline,45,p.pot);p.pac=clamp(p.pac-decline,20,99);if(priorAge>=35)p.phy=clamp(p.phy-decline,20,99)}
  resetSeasonStats(p);recalcPlayer(p)
}
function finishSeason(){const row=s.table[0],rank=sortedTable().findIndex((x:TableRow)=>x.id===0)+1,prize=rank===1?22e7:rank<=4?15e7:rank<=8?9e7:rank<=14?6e7:4e7;saveBest(row.pts);s.complete=true;s.history.push({season:s.season,rank,points:row.pts,record:`${row.w}勝${row.d}分${row.l}敗`,prize});q("[data-result]").textContent+=`｜シーズン終了：${rank}位 ${row.pts}pt`;save(s);render()}
function nextSeason(){
  if(!s.complete)return;const last=s.history[s.history.length-1],sponsor=last.rank===1?12e7:last.rank<=4?9e7:last.rank<=8?6e7:4e7;s.budget+=last.prize+sponsor;s.season++;
  const expired:Player[]=[];for(const p of s.squad){applyOffseasonDevelopment(p,true);p.contractYears=Math.max(0,p.contractYears-1);if(p.contractYears===0)expired.push(p)}
  for(const p of expired){if(s.squad.length-expired.length<18){p.contractYears=1;p.wage=Math.round(p.wage*1.12/10000)*10000;s.log.push(`契約切れ緊急延長：${p.name} 1年`);continue}const buyer=foreignClubs[(hashText(p.id+s.season)%foreignClubs.length)];s.squad=s.squad.filter((x:Player)=>x.id!==p.id);addToClub(p,buyer.id);p.contractYears=2+hashText(p.id)%3;s.transferHistory.push({season:s.season,week:0,type:"FREE",player:p.name,club:buyer.name,fee:0});s.log.push(`契約満了：${p.name} → ${buyer.name}`)}
  for(const p of allOpponentPlayers(s)){applyOffseasonDevelopment(p,false);p.contractYears--;if(p.contractYears<=0)p.contractYears=2+(hashText(p.id+s.season)%4)}
  const retired=s.squad.filter((p:Player)=>p.age>=37&&Math.random()<.45).map((p:Player)=>p.id);if(retired.length){s.squad=s.squad.filter((p:Player)=>!retired.includes(p.id));s.log.push(retired.length+"名が引退")}
  const youthCount=s.facilities.academy?2:1;for(let i=0;i<youthCount;i++)s.squad.push(makeYouth(s.seed+s.season*12347,i));while(s.squad.length<20)s.squad.push(makeYouth(newSeed(),s.squad.length));
  s.week=1;s.table=tableFresh();s.form=[];s.feed=[];s.lastNet=0;s.match=null;s.complete=false;s.marketWindow=1;s.offers=[];s.negotiation=null;autoLineup();s.selectedPlayer=s.lineup[0];root.dataset.state="running";s.log.push(`SEASON ${s.season} 開幕：スポンサー ${yen(sponsor)} / ユース ${youthCount}名加入。全盛期の能力は原則維持、若手は成長、ベテランのみ緩やかに変化。`);save(s);render()
}function playerProfile(p?:Player){
  if(!p)return;const owned=s.squad.some((x:Player)=>x.id===p.id),known=owned||p.scouted;q("[data-player-owned]").textContent=owned?"Harbor City FC":`${p.country} / ${p.clubName}`;
  const details=known?`${statBar("PAC",p.pac)}${statBar("SHO",p.sho)}${statBar("PAS",p.pas)}${statBar("DRI",p.dri)}${statBar("DEF",p.def)}${statBar("PHY",p.phy)}`:`<div class="unknown-stats">詳細能力はスカウトで開示。OVR・シーズン成績・契約状況は確認できます。</div>`;
  const meta=`<div class="profile-meta-grid"><span>POT <b>${known?p.pot:"??"}</b></span><span>TRAIT <b>${known?esc(p.trait):"SCOUT"}</b></span><span>VALUE <b>${yen(p.value)}</b></span><span>給与/節 <b>${yen(p.wage)}</b></span><span>CLUB <b>${esc(p.clubName)}</b></span><span>契約 <b class="${p.contractYears<=1?"contract-alert":""}">${p.contractYears}年</b></span></div>`;
  const records=`<div class="profile-record"><span>出場 <b>${p.apps}</b></span><span>得点 <b>${p.goals}</b></span><span>アシスト <b>${p.assists}</b></span><span>MOM <b>${p.mom}</b></span><span>平均評価 <b>${p.avgRating?p.avgRating.toFixed(2):"--"}</b></span><span>調子 <b>${p.form.toFixed(1)} ${formText(p)}</b></span></div>`;
  const actions=owned?`<div class="profile-actions"><button class="sim-secondary" type="button" data-renew-player="${p.id}">契約更新を交渉</button><button class="sim-secondary" type="button" data-list-player="${p.id}">${p.transferListed?"移籍リスト解除":"移籍リストに出す"}</button></div>`:`<div class="profile-actions"><button class="sim-secondary" type="button" data-profile-scout="${p.id}" ${known||s.budget<2e6?"disabled":""}>${known?"SCOUTED":"スカウト ¥2,000,000"}</button><button class="sim-primary profile-negotiate" type="button" data-negotiate-player="${p.id}" ${!transferWindowOpen()?"disabled":""}>移籍交渉を開始</button></div>`;
  q("[data-player-detail]").innerHTML=`<div class="profile-hero"><div><span class="profile-flag">${p.nation}</span><h4>${esc(p.name)}</h4><p>${p.pos.join(" / ")} ・ ${p.age}歳${p.injury>0?" ・ 🚑あと"+p.injury+"節":""}</p></div><strong class="profile-ovr">${p.ovr}<small>OVR</small></strong></div>${meta}<div class="profile-stats">${details}</div>${records}${actions}`;
  root.querySelector<HTMLButtonElement>("[data-renew-player]")?.addEventListener("click",()=>startRenewal(p.id));root.querySelector<HTMLButtonElement>("[data-list-player]")?.addEventListener("click",()=>toggleTransferList(p.id));root.querySelector<HTMLButtonElement>("[data-profile-scout]")?.addEventListener("click",()=>scoutPlayer(p.id));root.querySelector<HTMLButtonElement>("[data-negotiate-player]")?.addEventListener("click",()=>startTransferNegotiation(p.id));
}
function statBar(label:string,v:number){return`<div class="player-stat"><span>${label}</span><progress max="100" value="${v}"></progress><b>${Math.round(v)}</b></div>`}
function formText(p:Player){return p.form>=4.3?"🔥":p.form>=3.5?"↗":p.form<=2?"↓":"→"}function render(){
  syncBench();const row=s.table[0] as TableRow,rank=sortedTable().findIndex((x:TableRow)=>x.id===0)+1,ls=lineStats(),best=readBest(),pay=payroll(),fx=currentFixture(),opp=leagueClubs[fx.oppId];root.dataset.seasonId=String(s.seed)+"-"+s.season;root.dataset.matchPhase=s.match?.phase||"pre";root.classList.toggle("halftime-active",s.match?.phase==="halftime");
  q("[data-best]").textContent=best?best+" pt":"0 pt";q("[data-season]").textContent=s.season+"年目";q("[data-week]").textContent=Math.min(s.week,TOTAL_MATCHES)+" / "+TOTAL_MATCHES;q("[data-points]").textContent=String(row.pts);q("[data-rank]").textContent=s.week===1&&row.p===0?"順位 --":rank+"位";q("[data-budget]").textContent=yen(s.budget);q("[data-finance-note]").textContent="給与/節 "+yen(pay);q("[data-quality]").textContent=ls.ovr.toFixed(1);q("[data-chemistry]").textContent="適性 "+Math.round(ls.fit)+"%";q("[data-fans]").textContent=Math.round(s.fans).toLocaleString("ja-JP");q("[data-record]").textContent=`${row.w}勝 ${row.d}分 ${row.l}敗`;q("[data-attack]").textContent=ls.attack.toFixed(1);q("[data-midfield]").textContent=ls.mid.toFixed(1);q("[data-defense]").textContent=ls.def.toFixed(1);
  (root.querySelector<HTMLProgressElement>("[data-fitness]")!).value=ls.fitness;(root.querySelector<HTMLProgressElement>("[data-morale]")!).value=ls.form*20;q("[data-fitness-text]").textContent=Math.round(ls.fitness)+"";q("[data-morale-text]").textContent=ls.form.toFixed(1);q("[data-opponent-badge]").textContent=(fx.home?"HOME vs ":"AWAY vs ")+opp.name;q("[data-opponent-level]").textContent=`${opp.name} / OVR ${Math.round(clubStrength(fx.oppId))}`;q("[data-scout]").textContent=opp.ovr>=74?"相手分析：上位級。後半の交代と疲労管理が重要。":opp.ovr<=67?"相手分析：優位。取りこぼしを避けたい。":"相手分析：互角。配置適性・調子・戦術相性が勝負を分ける。";
  const tbl=sortedTable();q("[data-league-table]").innerHTML=tbl.map((r:TableRow,i:number)=>`<tr class="${r.id===0?"user-team":""}"><td>${i+1}</td><td>${esc(r.name)}</td><td>${r.p}</td><td>${r.w}</td><td>${r.d}</td><td>${r.l}</td><td>${r.gf}</td><td>${r.ga}</td><td>${r.gf-r.ga>=0?"+":""}${r.gf-r.ga}</td><td><b>${r.pts}</b></td></tr>`).join("");q("[data-table-note]").textContent="第"+Math.min(TOTAL_MATCHES,s.week-1)+"節終了";
  let fc=0;Object.keys(facilityCosts).forEach(k=>{const b=qb(`[data-facility="${k}"]`);if(s.facilities[k]){fc++;b.disabled=true;b.textContent="完成"}else{b.disabled=s.budget<facilityCosts[k]||!!s.match;b.textContent=yen(facilityCosts[k])}});q("[data-facility-count]").textContent=fc+" / 4";q("[data-payroll]").textContent=yen(pay);q("[data-net-income]").textContent=(s.lastNet>=0?"+":"")+yen(s.lastNet);q("[data-squad-value]").textContent=yen(s.squad.reduce((a:number,p:Player)=>a+p.value,0));q("[data-log]").innerHTML=s.log.slice(-8).reverse().map((x:string)=>"<li>"+esc(x)+"</li>").join("");q("[data-match-feed]").innerHTML=s.feed.length?s.feed.map((x:string)=>"<div>"+x+"</div>").join(""):`<div>キックオフすると試合経過が表示されます。</div>`;
  qs("[data-formation]").value=s.formation;qs("[data-formation]").disabled=!!s.match;qs("[data-training]").disabled=!!s.match;qb("[data-auto-lineup]").disabled=!!s.match;qb("[data-market-refresh]").disabled=!!s.match||s.budget<5e6;qb("[data-match]").textContent=s.match?.phase==="halftime"?"後半開始 → FULL TIME":"キックオフ → 前半";qb("[data-match]").disabled=s.complete;qb("[data-quick-match]").disabled=s.complete||!!s.match;
  q("[data-game-over]").hidden=!s.complete;if(s.complete){root.dataset.state="complete";const last=s.history[s.history.length-1];if(last){q("[data-final-points]").textContent=last.points+" pt / "+last.rank+"位";q("[data-final-comment]").textContent=last.rank===1?"38試合を戦い抜いてリーグ制覇。次は王者として連覇へ。":last.rank<=4?"TOP4達成。欧州市場と契約管理でさらに上を狙えます。":"38試合完走。補強と契約更新で次のシーズンへ。";q("[data-season-reward]").textContent="順位賞金 "+yen(last.prize)+" ＋ 来季スポンサー収入"}}else root.dataset.state="running";
  renderPitch();renderLineupEditor();renderBench();renderSquad();renderMarket();renderWorld();renderOffers();renderLeaders();renderHalftime();renderTransferHistory();renderHistory();playerProfile(playerById(s.selectedPlayer)||s.squad[0]);
}function activateTab(name:string){root.querySelectorAll<HTMLElement>("[data-football-panel]").forEach(el=>el.hidden=el.dataset.footballPanel!==name);root.querySelectorAll<HTMLButtonElement>("[data-football-tab]").forEach(b=>b.classList.toggle("active",b.dataset.footballTab===name))}
function start(load=false){const stored=load?read():null;s=stored||fresh();if(!s.squad?.length||!s.rivalSquads||!s.worldSquads||!s.table){s=fresh()}intro.hidden=true;play.hidden=false;syncBench();render();save(s)}
root.querySelectorAll<HTMLButtonElement>("[data-football-tab]").forEach(b=>b.onclick=()=>activateTab(b.dataset.footballTab!));activateTab("squad");
qb("[data-start]").onclick=()=>start(false);const cont=qb("[data-continue]");cont.hidden=!read();cont.onclick=()=>start(true);qb("[data-restart]").onclick=()=>{clear();start(false)};qb("[data-next-season]").onclick=nextSeason;
qs("[data-formation]").onchange=()=>{s.formation=qs("[data-formation]").value;autoLineup();save(s);render()};qb("[data-auto-lineup]").onclick=()=>{autoLineup();save(s);render()};qb("[data-market-refresh]").onclick=refreshMarket;qb("[data-make-sub]").onclick=makeSub;
qs("[data-market-country]").onchange=()=>{s.marketCountry=qs("[data-market-country]").value;s.marketClub="ALL";save(s);renderMarket()};qs("[data-market-club]").onchange=()=>{s.marketClub=qs("[data-market-club]").value;save(s);renderMarket()};qs("[data-market-filter]").onchange=renderMarket;qs("[data-market-sort]").onchange=renderMarket;
qs("[data-world-country]").onchange=()=>{s.worldCountry=qs("[data-world-country]").value;const clubs=clubsForCountry(s.worldCountry);s.activeWorldClub=clubs[0]?.id||"1";save(s);renderWorld()};qs("[data-world-club]").onchange=()=>{s.activeWorldClub=qs("[data-world-club]").value;save(s);renderWorld()};
root.querySelectorAll<HTMLButtonElement>("[data-facility]").forEach(b=>b.onclick=()=>{const k=b.dataset.facility!;if(s.facilities[k]||s.budget<facilityCosts[k]||s.match)return;s.budget-=facilityCosts[k];s.facilities[k]=true;s.log.push("施設完成："+k);save(s);render()});
qb("[data-match]").onclick=()=>{if(s.complete)return;if(s.match?.phase==="halftime")finishMatch();else if(!s.match)kickoff()};qb("[data-quick-match]").onclick=quickMatch;

export {};
export function bootFootball(load = false) { start(load); }
