export {};
import { qs, request, setError, loadJson, saveJson, touchRecent, copyShare } from "./shared-client";
type Participant={id:string;name:string};type Data={id:string;title:string;description:string;expiresAt:number;participants:Participant[];participantCount:number;drawn:boolean;order:Participant[]};
const loading=qs<HTMLElement>("[data-loading]")!,create=qs<HTMLElement>("[data-create]")!,event=qs<HTMLElement>("[data-event]")!,notFound=qs<HTMLElement>("[data-not-found]")!;
const params=new URLSearchParams(location.search),id=params.get("id")??"";let current:Data|null=null;
const adminKey=(x:string)=>"utility-tools:lottery:admin:"+x,joinKey=(x:string)=>"utility-tools:lottery:join:"+x;
touchRecent({id:"shared-lottery-order",href:"/lottery-order/",name:"順番決め・くじ引き",category:"share"});
const errors={name_required:"名前を入力してください。",name_already_used:"同じ名前の参加者がいます。",already_drawn:"抽選済みです。",at_least_two_participants:"2人以上参加してから抽選してください。"} as Record<string,string>;
function initCreate(){loading.hidden=true;create.hidden=false;const f=qs<HTMLFormElement>("[data-create-form]")!,e=qs<HTMLElement>("[data-create-error]")!;f.addEventListener("submit",async ev=>{ev.preventDefault();const fd=new FormData(f);try{const r=await request("/api/collab/lottery",{method:"POST",body:JSON.stringify({title:fd.get("title"),description:fd.get("description")})},errors);localStorage.setItem(adminKey(r.id),r.adminToken);location.assign("/lottery-order/?id="+r.id+"&created=1")}catch(x){setError(e,x instanceof Error?x.message:"作成に失敗しました。")}})}
function saved(){return loadJson<any|null>(joinKey(id),null)}
function render(){if(!current)return;qs<HTMLElement>("[data-title]")!.textContent=current.title;const d=qs<HTMLElement>("[data-description]")!;d.textContent=current.description;d.hidden=!current.description;qs<HTMLElement>("[data-count]")!.textContent=current.participantCount+"人参加";qs<HTMLElement>("[data-expiry]")!.textContent="保存期限: "+new Date(current.expiresAt).toLocaleDateString("ja-JP");qs<HTMLInputElement>("[data-share-url]")!.value=location.origin+"/lottery-order/?id="+id;qs<HTMLElement>("[data-created]")!.hidden=params.get("created")!=="1";const admin=localStorage.getItem(adminKey(id));qs<HTMLButtonElement>("[data-delete]")!.hidden=!admin;qs<HTMLButtonElement>("[data-draw]")!.hidden=!admin||current.drawn;const sv=saved();qs<HTMLButtonElement>("[data-leave]")!.hidden=!sv||current.drawn;qs<HTMLButtonElement>("[data-join]")!.disabled=current.drawn;qs<HTMLInputElement>("[data-name]")!.disabled=current.drawn;const list=qs<HTMLElement>("[data-participants]")!;list.replaceChildren();for(const p of current.participants){const el=document.createElement("div");el.className="participant";el.textContent=p.name;list.append(el)}const result=qs<HTMLElement>("[data-result]")!;result.replaceChildren();qs<HTMLElement>("[data-not-drawn]")!.hidden=current.drawn;if(current.drawn)current.order.forEach((p,i)=>{const row=document.createElement("div");row.className="rank-row";const n=document.createElement("b");n.textContent=String(i+1);const s=document.createElement("strong");s.textContent=p.name;row.append(n,s);result.append(row)})}
async function reload(){current=await request("/api/collab/lottery/"+id,undefined,errors);render()}
function wire(){const f=qs<HTMLFormElement>("[data-join-form]")!,err=qs<HTMLElement>("[data-join-error]")!;f.addEventListener("submit",async e=>{e.preventDefault();if(saved()){setError(err,"この端末では参加登録済みです。");return}try{const r=await request("/api/collab/lottery/"+id+"/join",{method:"POST",body:JSON.stringify({name:qs<HTMLInputElement>("[data-name]")!.value})},errors);saveJson(joinKey(id),{participantId:r.participantId,editToken:r.editToken});await reload();setError(err)}catch(x){setError(err,x instanceof Error?x.message:"参加登録に失敗しました。")}});qs<HTMLButtonElement>("[data-leave]")!.addEventListener("click",async()=>{const sv=saved();if(!sv||!confirm("参加を取り消しますか？"))return;await request("/api/collab/lottery/"+id+"/join/"+sv.participantId,{method:"DELETE",headers:{authorization:"Bearer "+sv.editToken}},errors);localStorage.removeItem(joinKey(id));await reload()});qs<HTMLButtonElement>("[data-draw]")!.addEventListener("click",async()=>{const token=localStorage.getItem(adminKey(id));if(!token||!confirm("現在の参加者で順番を確定しますか？"))return;await request("/api/collab/lottery/"+id+"/draw",{method:"POST",headers:{authorization:"Bearer "+token},body:"{}"},errors);await reload()});qs<HTMLButtonElement>("[data-copy]")!.addEventListener("click",()=>copyShare(qs<HTMLInputElement>("[data-share-url]")!,qs<HTMLElement>("[data-copy-message]")!));qs<HTMLButtonElement>("[data-delete]")!.addEventListener("click",async()=>{const token=localStorage.getItem(adminKey(id));if(!token||!confirm("この抽選を削除しますか？"))return;await request("/api/collab/lottery/"+id,{method:"DELETE",headers:{authorization:"Bearer "+token}},errors);location.assign("/lottery-order/")})}
if(id){wire();reload().then(()=>{loading.hidden=true;event.hidden=false}).catch(()=>{loading.hidden=true;notFound.hidden=false})}else initCreate();