export {};
import { qs, request, setError, loadJson, saveJson, touchRecent, copyShare } from "./shared-client";
type Item={id:number;label:string;assignment:{id:string;name:string}|null};type Data={id:string;title:string;description:string;expiresAt:number;items:Item[];assignedCount:number};
const loading=qs<HTMLElement>("[data-loading]")!,create=qs<HTMLElement>("[data-create]")!,event=qs<HTMLElement>("[data-event]")!,notFound=qs<HTMLElement>("[data-not-found]")!;
const params=new URLSearchParams(location.search),id=params.get("id")??"";let current:Data|null=null;
const adminKey=(x:string)=>"utility-tools:packing:admin:"+x,claimsKey=(x:string)=>"utility-tools:packing:claims:"+x;
touchRecent({id:"packing-assignment",href:"/packing-list/",name:"持ち物分担表",category:"share"});
const errors={items_required:"持ち物を1件以上入力してください。",name_required:"名前を入力してください。",already_assigned:"その項目はすでに担当が決まっています。"} as Record<string,string>;
function claims(){return loadJson<Record<string,{claimId:string;editToken:string}>>(claimsKey(id),{})}
function initCreate(){loading.hidden=true;create.hidden=false;const f=qs<HTMLFormElement>("[data-create-form]")!,err=qs<HTMLElement>("[data-create-error]")!;f.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(f),items=[...new Set(String(fd.get("items")??"").split(/\r?\n/).map(v=>v.trim()).filter(Boolean))];if(!items.length){setError(err,"持ち物を1件以上入力してください。");return}try{const r=await request("/api/collab/packing",{method:"POST",body:JSON.stringify({title:fd.get("title"),description:fd.get("description"),items})},errors);localStorage.setItem(adminKey(r.id),r.adminToken);location.assign("/packing-list/?id="+r.id+"&created=1")}catch(x){setError(err,x instanceof Error?x.message:"作成に失敗しました。")}})}
function render(){if(!current)return;qs<HTMLElement>("[data-title]")!.textContent=current.title;const desc=qs<HTMLElement>("[data-description]")!;desc.textContent=current.description;desc.hidden=!current.description;qs<HTMLElement>("[data-progress]")!.textContent=current.assignedCount+" / "+current.items.length+" 担当済み";qs<HTMLElement>("[data-expiry]")!.textContent="保存期限: "+new Date(current.expiresAt).toLocaleDateString("ja-JP");qs<HTMLInputElement>("[data-share-url]")!.value=location.origin+"/packing-list/?id="+id;qs<HTMLElement>("[data-created]")!.hidden=params.get("created")!=="1";qs<HTMLButtonElement>("[data-delete]")!.hidden=!localStorage.getItem(adminKey(id));const list=qs<HTMLElement>("[data-list]")!;list.replaceChildren();const mine=claims();for(const item of current.items){const row=document.createElement("div");row.className="packing-item"+(item.assignment?" is-assigned":"");const copy=document.createElement("div");copy.className="packing-copy";const strong=document.createElement("strong");strong.textContent=item.label;const sub=document.createElement("span");sub.textContent=item.assignment?"担当: "+item.assignment.name:"未担当";copy.append(strong,sub);const btn=document.createElement("button");btn.className="button "+(item.assignment?"button-secondary":"button-primary");btn.type="button";const own=item.assignment&&mine[String(item.id)]?.claimId===item.assignment.id;btn.textContent=own?"担当を外す":item.assignment?"担当済み":"担当する";btn.disabled=Boolean(item.assignment&&!own);btn.addEventListener("click",()=>own?release(item):claim(item));row.append(copy,btn);list.append(row)}}
async function reload(){current=await request("/api/collab/packing/"+id,undefined,errors);render()}
async function claim(item:Item){const err=qs<HTMLElement>("[data-error]")!,name=qs<HTMLInputElement>("[data-name]")!.value.trim();if(!name){setError(err,"名前を入力してください。");return}try{const r=await request("/api/collab/packing/"+id+"/claim",{method:"POST",body:JSON.stringify({itemId:item.id,name})},errors);const map=claims();map[String(item.id)]={claimId:r.claimId,editToken:r.editToken};saveJson(claimsKey(id),map);setError(err);await reload()}catch(x){setError(err,x instanceof Error?x.message:"担当登録に失敗しました。")}}
async function release(item:Item){const map=claims(),saved=map[String(item.id)];if(!saved||!confirm("担当を外しますか？"))return;await request("/api/collab/packing/"+id+"/claim/"+saved.claimId,{method:"DELETE",headers:{authorization:"Bearer "+saved.editToken}},errors);delete map[String(item.id)];saveJson(claimsKey(id),map);await reload()}
function wire(){qs<HTMLButtonElement>("[data-copy]")!.addEventListener("click",()=>copyShare(qs<HTMLInputElement>("[data-share-url]")!,qs<HTMLElement>("[data-copy-message]")!));qs<HTMLButtonElement>("[data-delete]")!.addEventListener("click",async()=>{const token=localStorage.getItem(adminKey(id));if(!token||!confirm("この分担表を削除しますか？"))return;await request("/api/collab/packing/"+id,{method:"DELETE",headers:{authorization:"Bearer "+token}},errors);location.assign("/packing-list/")})}
if(id){wire();reload().then(()=>{loading.hidden=true;event.hidden=false}).catch(()=>{loading.hidden=true;notFound.hidden=false})}else initCreate();