export {};
import { qs, request, setError, loadJson, saveJson, touchRecent, copyShare } from "./shared-client";
type Task={id:string;label:string;done:boolean};type Data={id:string;title:string;description:string;expiresAt:number;tasks:Task[];doneCount:number};
const loading=qs<HTMLElement>("[data-loading]")!,create=qs<HTMLElement>("[data-create]")!,event=qs<HTMLElement>("[data-event]")!,notFound=qs<HTMLElement>("[data-not-found]")!;
const params=new URLSearchParams(location.search),id=params.get("id")??"";let current:Data|null=null;
const adminKey=(x:string)=>"utility-tools:checklist:admin:"+x,taskKey=(x:string)=>"utility-tools:checklist:tasks:"+x;
touchRecent({id:"shared-checklist",href:"/shared-checklist/",name:"共有TODO・チェックリスト",category:"share"});
const errors={tasks_required:"TODOを1件以上入力してください。",task_required:"TODOを入力してください。",task_limit:"TODOの上限に達しました。"} as Record<string,string>;
function tokens(){return loadJson<Record<string,string>>(taskKey(id),{})}
function initCreate(){loading.hidden=true;create.hidden=false;const f=qs<HTMLFormElement>("[data-create-form]")!,err=qs<HTMLElement>("[data-create-error]")!;f.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(f),tasks=[...new Set(String(fd.get("tasks")??"").split(/\r?\n/).map(v=>v.trim()).filter(Boolean))];if(!tasks.length){setError(err,"TODOを1件以上入力してください。");return}try{const r=await request("/api/collab/checklist",{method:"POST",body:JSON.stringify({title:fd.get("title"),description:fd.get("description"),tasks})},errors);localStorage.setItem(adminKey(r.id),r.adminToken);location.assign("/shared-checklist/?id="+r.id+"&created=1")}catch(x){setError(err,x instanceof Error?x.message:"作成に失敗しました。")}})}
function render(){if(!current)return;qs<HTMLElement>("[data-title]")!.textContent=current.title;const desc=qs<HTMLElement>("[data-description]")!;desc.textContent=current.description;desc.hidden=!current.description;qs<HTMLElement>("[data-progress]")!.textContent=current.doneCount+" / "+current.tasks.length+" 完了";qs<HTMLElement>("[data-expiry]")!.textContent="保存期限: "+new Date(current.expiresAt).toLocaleDateString("ja-JP");qs<HTMLInputElement>("[data-share-url]")!.value=location.origin+"/shared-checklist/?id="+id;qs<HTMLElement>("[data-created]")!.hidden=params.get("created")!=="1";qs<HTMLButtonElement>("[data-delete]")!.hidden=!localStorage.getItem(adminKey(id));const list=qs<HTMLElement>("[data-list]")!;list.replaceChildren();const map=tokens();for(const task of current.tasks){const row=document.createElement("div");row.className="check-row"+(task.done?" is-done":"");const input=document.createElement("input");input.type="checkbox";input.checked=task.done;input.addEventListener("change",()=>toggle(task,input.checked));const span=document.createElement("span");span.textContent=task.label;row.append(input,span);if(map[task.id]){const b=document.createElement("button");b.type="button";b.textContent="削除";b.addEventListener("click",()=>removeTask(task));row.append(b)}list.append(row)}}
async function reload(){current=await request("/api/collab/checklist/"+id,undefined,errors);render()}
async function toggle(task:Task,done:boolean){try{await request("/api/collab/checklist/"+id+"/task/"+task.id,{method:"PUT",body:JSON.stringify({done})},errors);await reload()}catch{await reload()}}
async function removeTask(task:Task){const map=tokens(),token=map[task.id];if(!token||!confirm("このTODOを削除しますか？"))return;await request("/api/collab/checklist/"+id+"/task/"+task.id,{method:"DELETE",headers:{authorization:"Bearer "+token}},errors);delete map[task.id];saveJson(taskKey(id),map);await reload()}
function wire(){const f=qs<HTMLFormElement>("[data-add-form]")!,err=qs<HTMLElement>("[data-error]")!;f.addEventListener("submit",async e=>{e.preventDefault();const input=qs<HTMLInputElement>("[data-new-task]")!,label=input.value.trim();if(!label)return;try{const r=await request("/api/collab/checklist/"+id+"/task",{method:"POST",body:JSON.stringify({label})},errors);const map=tokens();map[r.taskId]=r.editToken;saveJson(taskKey(id),map);input.value="";setError(err);await reload()}catch(x){setError(err,x instanceof Error?x.message:"追加に失敗しました。")}});qs<HTMLButtonElement>("[data-copy]")!.addEventListener("click",()=>copyShare(qs<HTMLInputElement>("[data-share-url]")!,qs<HTMLElement>("[data-copy-message]")!));qs<HTMLButtonElement>("[data-delete]")!.addEventListener("click",async()=>{const token=localStorage.getItem(adminKey(id));if(!token||!confirm("このチェックリストを削除しますか？"))return;await request("/api/collab/checklist/"+id,{method:"DELETE",headers:{authorization:"Bearer "+token}},errors);location.assign("/shared-checklist/")})}
if(id){wire();reload().then(()=>{loading.hidden=true;event.hidden=false}).catch(()=>{loading.hidden=true;notFound.hidden=false})}else initCreate();