export {};
import { qs, request, setError, loadJson, saveJson, touchRecent, copyShare } from "./shared-client";
type Q={id:number;text:string;type:"single"|"multiple"|"rating";options?:{id:number;label:string}[]};
type Data={id:string;title:string;description:string;expiresAt:number;questions:Q[];results:any[];responseCount:number};
const loading=qs<HTMLElement>("[data-loading]")!,create=qs<HTMLElement>("[data-create]")!,event=qs<HTMLElement>("[data-event]")!,notFound=qs<HTMLElement>("[data-not-found]")!;
const params=new URLSearchParams(location.search),id=params.get("id")??"";let current:Data|null=null;
const adminKey=(x:string)=>"utility-tools:survey:admin:"+x,responseKey=(x:string)=>"utility-tools:survey:response:"+x;
touchRecent({id:"simple-survey",href:"/survey/",name:"簡易アンケート",category:"share"});
const errors={questions_required:"有効な質問を1つ以上入力してください。",invalid_answers:"すべての質問に回答してください。",response_limit:"回答上限に達しました。"} as Record<string,string>;
function parseQuestions(text:string){return text.split(/\n\s*\n/).map(block=>block.split(/\r?\n/).map(v=>v.trim()).filter(Boolean)).filter(Boolean).map(lines=>{const m=lines[0]?.match(/^(単一|複数|評価)\s*[:：]\s*(.+)$/);if(!m)return null;const type=m[1]==="単一"?"single":m[1]==="複数"?"multiple":"rating";return type==="rating"?{text:m[2],type}:{text:m[2],type,options:lines.slice(1)}}).filter(Boolean).slice(0,10)}
function initCreate(){loading.hidden=true;create.hidden=false;const form=qs<HTMLFormElement>("[data-create-form]")!,err=qs<HTMLElement>("[data-create-error]")!,btn=qs<HTMLButtonElement>("[data-create-button]")!;form.addEventListener("submit",async e=>{e.preventDefault();setError(err);const fd=new FormData(form),questions=parseQuestions(String(fd.get("questions")??""));if(!questions.length){setError(err,"質問の形式を確認してください。");return}btn.disabled=true;try{const r=await request("/api/collab/survey",{method:"POST",body:JSON.stringify({title:fd.get("title"),description:fd.get("description"),questions})},errors);localStorage.setItem(adminKey(r.id),r.adminToken);location.assign("/survey/?id="+r.id+"&created=1")}catch(x){setError(err,x instanceof Error?x.message:"作成に失敗しました。");btn.disabled=false}})}
function saved(){return loadJson<any|null>(responseKey(id),null)}
function render(){if(!current)return;qs<HTMLElement>("[data-title]")!.textContent=current.title;const d=qs<HTMLElement>("[data-description]")!;d.textContent=current.description;d.hidden=!current.description;qs<HTMLElement>("[data-count]")!.textContent=current.responseCount+"件回答";qs<HTMLElement>("[data-expiry]")!.textContent="保存期限: "+new Date(current.expiresAt).toLocaleDateString("ja-JP");qs<HTMLInputElement>("[data-share-url]")!.value=location.origin+"/survey/?id="+id;qs<HTMLElement>("[data-created]")!.hidden=params.get("created")!=="1";qs<HTMLButtonElement>("[data-delete]")!.hidden=!localStorage.getItem(adminKey(id));const box=qs<HTMLElement>("[data-questions]")!;box.replaceChildren();const sv=saved();for(const q of current.questions){const wrap=document.createElement("div");wrap.className="survey-question";const h=document.createElement("h3");h.textContent=q.text;wrap.append(h);if(q.type==="rating"){const r=document.createElement("div");r.className="survey-rating";for(let i=1;i<=5;i++){const l=document.createElement("label"),inp=document.createElement("input"),sp=document.createElement("span");inp.type="radio";inp.name="q-"+q.id;inp.value=String(i);inp.checked=Number(sv?.answers?.[q.id])===i;sp.textContent=String(i);l.append(inp,sp);r.append(l)}wrap.append(r)}else for(const o of q.options??[]){const l=document.createElement("label"),inp=document.createElement("input"),sp=document.createElement("span");l.className="survey-option";inp.type=q.type==="multiple"?"checkbox":"radio";inp.name="q-"+q.id;inp.value=String(o.id);const old=sv?.answers?.[q.id];inp.checked=Array.isArray(old)?old.includes(o.id):Number(old)===o.id;sp.textContent=o.label;l.append(inp,sp);wrap.append(l)}box.append(wrap)}qs<HTMLElement>("[data-answer-heading]")!.textContent=sv?"回答を変更":"回答する";qs<HTMLButtonElement>("[data-answer-submit]")!.textContent=sv?"回答を更新":"回答を送信";qs<HTMLButtonElement>("[data-answer-delete]")!.hidden=!sv;const out=qs<HTMLElement>("[data-results]")!;out.replaceChildren();for(const q of current.questions){const res=current.results.find((x:any)=>x.questionId===q.id);const w=document.createElement("div");w.className="survey-result";const h=document.createElement("h3");h.textContent=q.text;w.append(h);if(q.type==="rating"){const a=document.createElement("div");a.className="result-average";a.textContent=(res?.average??0).toFixed(1)+" / 5";w.append(a)}else for(const o of q.options??[]){const c=res?.counts?.[String(o.id)]??0,p=current.responseCount?Math.round(c/current.responseCount*100):0;const line=document.createElement("div");line.innerHTML='<div class="result-line"><span></span><strong></strong></div><div class="result-bar"><span></span></div>';line.querySelector("span")!.textContent=o.label;line.querySelector("strong")!.textContent=c+"件 / "+p+"%";(line.querySelector(".result-bar span") as HTMLElement).style.width=p+"%";w.append(line)}out.append(w)}}
async function reload(){current=await request("/api/collab/survey/"+id,undefined,errors);render()}
function collect(){if(!current)return null;const answers:any={};for(const q of current.questions){const els=[...document.querySelectorAll<HTMLInputElement>('[name="q-'+q.id+'"]')];if(q.type==="multiple"){const vals=els.filter(x=>x.checked).map(x=>Number(x.value));if(!vals.length)return null;answers[q.id]=vals}else{const x=els.find(x=>x.checked);if(!x)return null;answers[q.id]=Number(x.value)}}return answers}
function wire(){const form=qs<HTMLFormElement>("[data-answer-form]")!,err=qs<HTMLElement>("[data-answer-error]")!;form.addEventListener("submit",async e=>{e.preventDefault();const answers=collect();if(!answers){setError(err,"すべての質問に回答してください。");return}const sv=saved();try{if(sv){await request("/api/collab/survey/"+id+"/survey-response/"+sv.responseId,{method:"PUT",headers:{authorization:"Bearer "+sv.editToken},body:JSON.stringify({answers})},errors);sv.answers=answers;saveJson(responseKey(id),sv)}else{const r=await request("/api/collab/survey/"+id+"/survey-response",{method:"POST",body:JSON.stringify({answers})},errors);saveJson(responseKey(id),{responseId:r.responseId,editToken:r.editToken,answers})}await reload();setError(err)}catch(x){setError(err,x instanceof Error?x.message:"回答に失敗しました。")}});qs<HTMLButtonElement>("[data-answer-delete]")!.addEventListener("click",async()=>{const sv=saved();if(!sv||!confirm("回答を取り消しますか？"))return;await request("/api/collab/survey/"+id+"/survey-response/"+sv.responseId,{method:"DELETE",headers:{authorization:"Bearer "+sv.editToken}},errors);localStorage.removeItem(responseKey(id));await reload()});qs<HTMLButtonElement>("[data-copy]")!.addEventListener("click",()=>copyShare(qs<HTMLInputElement>("[data-share-url]")!,qs<HTMLElement>("[data-copy-message]")!));qs<HTMLButtonElement>("[data-delete]")!.addEventListener("click",async()=>{const token=localStorage.getItem(adminKey(id));if(!token||!confirm("このアンケートを削除しますか？"))return;await request("/api/collab/survey/"+id,{method:"DELETE",headers:{authorization:"Bearer "+token}},errors);location.assign("/survey/")})}
if(id){wire();reload().then(()=>{loading.hidden=true;event.hidden=false}).catch(()=>{loading.hidden=true;notFound.hidden=false})}else initCreate();