export type ExtraToolFamily = "image" | "csv" | "text" | "pdf" | "qr" | "video" | "developer" | "utility" | "utilityplus";
export type ExtraToolCategory = "image" | "csv" | "json" | "text" | "pdf" | "qr" | "video" | "japanese" | "developer" | "date" | "calculator";

export type ExtraToolMeta = {
  id: string;
  mode: string;
  family: ExtraToolFamily;
  category: string;
  categoryKey: ExtraToolCategory;
  href: string;
  name: string;
  title: string;
  description: string;
  faqs: readonly (readonly [string, string])[];
};

const privacyFaq = ["入力したデータはサーバーに送信されますか？", "いいえ。このツールの処理はブラウザ内で完結します。"] as const;

export const extraTools: ExtraToolMeta[] = [
  {
    id: "image-compress", mode: "compress", family: "image", category: "画像", categoryKey: "image",
    href: "/image/compress/", name: "画像圧縮",
    title: "画像圧縮ツール｜JPG・PNG・WebPを無料で圧縮",
    description: "JPG・PNG・WebP画像をブラウザ内で圧縮し、容量を小さくします。",
    faqs: [["画質は調整できますか？", "はい。品質スライダーで圧縮率を調整できます。"], privacyFaq],
  },
  {
    id: "image-resize", mode: "resize", family: "image", category: "画像", categoryKey: "image",
    href: "/image/resize/", name: "画像サイズ変更",
    title: "画像サイズ変更ツール｜幅・高さを無料でリサイズ",
    description: "画像の幅・高さを指定してリサイズします。縦横比の維持にも対応します。",
    faqs: [["縦横比を維持できますか？", "はい。縦横比を維持したまま幅または高さを基準に変更できます。"], privacyFaq],
  },
  {
    id: "png-to-jpg", mode: "png-to-jpg", family: "image", category: "画像", categoryKey: "image",
    href: "/image/png-to-jpg/", name: "PNG → JPG変換",
    title: "PNGをJPGに変換｜無料・ブラウザ内処理",
    description: "PNG画像をJPEGへ変換します。透明部分の背景色も指定できます。",
    faqs: [["透明部分はどうなりますか？", "指定した背景色で塗りつぶしてJPEGへ変換します。"], privacyFaq],
  },
  {
    id: "webp-converter", mode: "webp-converter", family: "image", category: "画像", categoryKey: "image",
    href: "/image/webp-converter/", name: "WebP → JPG・PNG変換",
    title: "WebPをJPG・PNGに変換｜無料",
    description: "WebP画像をJPGまたはPNGへ変換します。",
    faqs: [["JPGとPNGのどちらに変換できますか？", "どちらも選択できます。"], privacyFaq],
  },  {
    id: "image-crop", mode: "crop", family: "image", category: "画像", categoryKey: "image",
    href: "/image/crop/", name: "画像トリミング",
    title: "画像トリミングツール｜範囲指定で切り抜き",
    description: "画像のX・Y座標と幅・高さを指定して切り抜きます。",
    faqs: [["切り抜く範囲は数値指定できますか？", "はい。開始位置と幅・高さをピクセル単位で指定できます。"], privacyFaq],
  },
  {
    id: "target-filesize", mode: "target-filesize", family: "image", category: "画像", categoryKey: "image",
    href: "/image/target-filesize/", name: "画像を指定容量以下に圧縮",
    title: "画像を500KB・1MB以下に圧縮｜容量指定",
    description: "目標容量をKBで指定し、JPEGまたはWebPの品質を自動調整します。",
    faqs: [["必ず指定容量以下になりますか？", "品質を下げても到達できない場合は、その時点で最小に近い結果を表示します。"], privacyFaq],
  },
  {
    id: "csv-merge", mode: "merge", family: "csv", category: "CSV", categoryKey: "csv",
    href: "/csv/merge/", name: "CSV結合",
    title: "CSV結合ツール｜複数CSVを1つにまとめる",
    description: "複数のCSVファイルを読み込み、列名を合わせて1つのCSVに結合します。",
    faqs: [["列の順番が違っても結合できますか？", "はい。ヘッダー名を基準に列を合わせます。"], privacyFaq],
  },
  {
    id: "csv-columns", mode: "columns", family: "csv", category: "CSV", categoryKey: "csv",
    href: "/csv/columns/", name: "CSV列削除・並べ替え",
    title: "CSVの列を削除・並べ替え｜無料",
    description: "CSVの列名を指定して、必要な列だけを好きな順番で出力します。",
    faqs: [["列の並べ替え方は？", "読み込み後に表示される列名をカンマ区切りで並べ直します。"], privacyFaq],
  },  {
    id: "csv-encoding", mode: "encoding", family: "csv", category: "CSV", categoryKey: "csv",
    href: "/csv/encoding/", name: "CSV文字コード変換",
    title: "CSV文字コード変換｜UTF-8・Shift_JIS対応",
    description: "CSVをUTF-8、BOM付きUTF-8、Shift_JISへブラウザ内で変換します。",
    faqs: [["Shift_JISに対応していますか？", "はい。UTF-8系とShift_JISの相互変換に対応します。"], privacyFaq],
  },
  {
    id: "csv-json", mode: "csv-json", family: "csv", category: "CSV・JSON", categoryKey: "csv",
    href: "/csv/json-converter/", name: "CSV ⇔ JSON変換",
    title: "CSVとJSONを相互変換｜無料",
    description: "CSVをJSONへ、JSON配列をCSVへ相互変換します。",
    faqs: [["JSONはどんな形式に対応しますか？", "オブジェクトの配列をCSVへ変換できます。"], privacyFaq],
  },
  {
    id: "json-formatter", mode: "json-formatter", family: "text", category: "テキスト", categoryKey: "text",
    href: "/text/json-formatter/", name: "JSON整形・圧縮・構文チェック",
    title: "JSON整形・圧縮・構文チェック｜無料",
    description: "JSONを読みやすく整形、1行に圧縮、構文エラーを確認できます。",
    faqs: [["JSONのエラーも分かりますか？", "はい。JSON.parseで検出した構文エラーを表示します。"], privacyFaq],
  },
  {
    id: "character-count", mode: "character-count", family: "text", category: "テキスト", categoryKey: "text",
    href: "/text/character-count/", name: "文字数カウント",
    title: "文字数カウント｜文字・行・バイト数を即時計測",
    description: "入力テキストの文字数、空白除外文字数、行数、UTF-8バイト数を数えます。",
    faqs: [["改行も文字数に含まれますか？", "通常の文字数には含まれます。行数は別に表示します。"], privacyFaq],
  },  {
    id: "fullwidth-halfwidth", mode: "fullwidth-halfwidth", family: "text", category: "テキスト", categoryKey: "text",
    href: "/text/fullwidth-halfwidth/", name: "全角・半角変換",
    title: "全角・半角変換｜英数字・スペースを一括変換",
    description: "英数字・記号・スペースを全角または半角へ一括変換します。",
    faqs: [["日本語の漢字やひらがなも変わりますか？", "いいえ。主にASCII範囲の英数字・記号とスペースを対象にします。"], privacyFaq],
  },
  {
    id: "newline-converter", mode: "newline-converter", family: "text", category: "テキスト", categoryKey: "text",
    href: "/text/newline-converter/", name: "改行削除・置換",
    title: "改行削除・置換ツール｜空白・カンマへ一括変換",
    description: "改行を削除したり、空白・カンマ・任意文字列へ置換します。",
    faqs: [["CRLFとLFの両方に対応しますか？", "はい。Windows・Unix系の改行をまとめて処理します。"], privacyFaq],
  },
  {
    id: "csv-duplicates", mode: "csv-duplicates", family: "utility", category: "CSV", categoryKey: "csv",
    href: "/csv/find-duplicates/", name: "CSV重複行検出",
    title: "CSV重複行検出｜重複レコードをブラウザ内で確認",
    description: "CSV内で完全一致する重複行を検出し、重複回数付きで一覧化します。",
    faqs: [["何を重複と判定しますか？", "すべての列の値が一致する行を重複として判定します。"], privacyFaq],
  },
  {
    id: "csv-remove-empty", mode: "csv-remove-empty", family: "utility", category: "CSV", categoryKey: "csv",
    href: "/csv/remove-empty-rows/", name: "CSV空行削除",
    title: "CSV空行削除｜空のレコードを無料で一括削除",
    description: "CSVを正しく解析し、すべての列が空の行だけを削除して保存します。",
    faqs: [["ヘッダーは残りますか？", "はい。先頭行はヘッダーとしてそのまま残します。"], privacyFaq],
  },
  {
    id: "csv-tsv", mode: "csv-tsv", family: "utility", category: "CSV", categoryKey: "csv",
    href: "/csv/tsv-converter/", name: "CSV ⇔ TSV変換",
    title: "CSVとTSVを相互変換｜タブ区切り・カンマ区切り",
    description: "CSVをTSVへ、TSVをCSVへ相互変換し、ファイルとして保存できます。",
    faqs: [["引用符付きの値にも対応しますか？", "はい。CSV/TSVパーサーで区切り文字や引用符を解析します。"], privacyFaq],
  },
  {
    id: "jsonl-json", mode: "jsonl-json", family: "utility", category: "JSON", categoryKey: "json",
    href: "/json/jsonl-converter/", name: "JSON Lines ⇔ JSON変換",
    title: "JSON LinesとJSON配列を相互変換｜JSONL変換",
    description: "1行1JSONのJSON Linesと通常のJSON配列を相互変換します。",
    faqs: [["JSON Linesとは何ですか？", "1行ごとに独立したJSONオブジェクトを記述する形式です。"], privacyFaq],
  },
  {
    id: "invisible-chars", mode: "invisible-chars", family: "utility", category: "テキスト", categoryKey: "text",
    href: "/text/invisible-characters/", name: "不可視文字検出",
    title: "不可視文字検出｜ゼロ幅スペース・NBSP・タブを確認",
    description: "テキスト内のゼロ幅スペース、NBSP、タブ、改行など見えにくい文字を位置付きで検出します。",
    faqs: [["どんな文字を検出しますか？", "ゼロ幅スペース、各種空白、タブ、改行、BOMなどを検出します。"], privacyFaq],
  },
  {
    id: "unicode-normalize", mode: "unicode-normalize", family: "utility", category: "テキスト", categoryKey: "text",
    href: "/text/unicode-normalize/", name: "Unicode正規化",
    title: "Unicode正規化｜NFC・NFKC・NFD・NFKD変換",
    description: "Unicode文字列をNFC、NFKC、NFD、NFKDの各形式へ正規化します。",
    faqs: [["NFKCは何に使えますか？", "互換文字をまとめたい場合などに利用できます。"], privacyFaq],
  },
  {
    id: "kana-converter", mode: "kana-converter", family: "utility", category: "日本語", categoryKey: "japanese",
    href: "/japanese/hiragana-katakana/", name: "ひらがな ⇔ カタカナ変換",
    title: "ひらがな・カタカナ変換｜相互変換ツール",
    description: "ひらがなをカタカナへ、カタカナをひらがなへ一括変換します。",
    faqs: [["漢字も変換されますか？", "いいえ。ひらがな・カタカナ部分だけを変換します。"], privacyFaq],
  },
  {
    id: "wareki", mode: "wareki", family: "utility", category: "日本語", categoryKey: "japanese",
    href: "/japanese/wareki/", name: "西暦 ⇔ 和暦変換",
    title: "西暦・和暦変換｜令和・平成・昭和・大正・明治",
    description: "西暦の日付と令和・平成・昭和・大正・明治の和暦を相互変換します。",
    faqs: [["どの元号に対応しますか？", "明治以降の主要元号に対応しています。"], privacyFaq],
  },
  {
    id: "base64", mode: "base64", family: "utility", category: "開発者", categoryKey: "developer",
    href: "/developer/base64/", name: "Base64エンコード・デコード",
    title: "Base64エンコード・デコード｜UTF-8対応",
    description: "日本語を含むUTF-8テキストをBase64へエンコード・デコードします。",
    faqs: [["日本語にも対応しますか？", "はい。UTF-8として安全に変換します。"], privacyFaq],
  },
  {
    id: "url-codec", mode: "url-codec", family: "utility", category: "開発者", categoryKey: "developer",
    href: "/developer/url-encode/", name: "URLエンコード・デコード",
    title: "URLエンコード・デコード｜パーセントエンコーディング",
    description: "URLに含める文字列をencodeURIComponent互換でエンコード・デコードします。",
    faqs: [["スペースや日本語も変換できますか？", "はい。URLコンポーネント向けに変換します。"], privacyFaq],
  },
  {
    id: "html-codec", mode: "html-codec", family: "utility", category: "開発者", categoryKey: "developer",
    href: "/developer/html-escape/", name: "HTMLエスケープ・解除",
    title: "HTMLエスケープ・アンエスケープ｜特殊文字変換",
    description: "HTMLの &, <, >, 引用符などを安全な文字参照へ変換・復元します。",
    faqs: [["どの文字をエスケープしますか？", "&、<、>、ダブルクォート、シングルクォートを変換します。"], privacyFaq],
  },
  {
    id: "sha", mode: "sha", family: "utility", category: "開発者", categoryKey: "developer",
    href: "/developer/sha/", name: "SHA-256・SHA-512生成",
    title: "SHA-256・SHA-512ハッシュ生成｜ブラウザ内計算",
    description: "入力テキストからSHA-256またはSHA-512のハッシュ値を生成します。",
    faqs: [["パスワード保存用ですか？", "単純なSHAハッシュ生成です。パスワード保存には専用のパスワードハッシュ方式を利用してください。"], privacyFaq],
  },
  {
    id: "file-sha", mode: "file-sha", family: "utility", category: "開発者", categoryKey: "developer",
    href: "/developer/file-hash/", name: "ファイルSHA-256・SHA-512計算",
    title: "ファイルSHA-256・SHA-512計算｜ハッシュ値確認",
    description: "選択したファイルのSHA-256またはSHA-512をブラウザ内で計算します。",
    faqs: [["ファイルはアップロードされますか？", "いいえ。ファイル内容はブラウザ内だけで読み込み、ハッシュを計算します。"], privacyFaq],
  },
  {
    id: "jwt-decode", mode: "jwt-decode", family: "utility", category: "開発者", categoryKey: "developer",
    href: "/developer/jwt-decode/", name: "JWTデコード",
    title: "JWTデコード｜Header・Payloadをブラウザ内で確認",
    description: "JWTのHeaderとPayloadをデコードして読みやすいJSONで表示します。",
    faqs: [["署名も検証できますか？", "いいえ。このツールは内容のデコードのみで、署名の正当性は検証しません。"], privacyFaq],
  },
  {
    id: "sql-in", mode: "sql-in", family: "utility", category: "開発者", categoryKey: "developer",
    href: "/developer/sql-in/", name: "SQL IN句生成",
    title: "SQL IN句生成｜改行・カンマ区切りから一括作成",
    description: "値の一覧からSQLのIN句に貼り付けられる形式を生成します。文字列のクォートも自動処理します。",
    faqs: [["シングルクォートを含む値はどうなりますか？", "SQL文字列として扱えるようシングルクォートを二重化します。"], privacyFaq],
  },
  {
    id: "line-prefix-suffix", mode: "line-prefix-suffix", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/line-prefix-suffix/", name: "各行の行頭・行末に文字追加",
    title: "各行の行頭・行末に文字を一括追加｜テキスト整形",
    description: "複数行テキストの各行へ、指定した接頭辞と接尾辞をまとめて追加します。",
    faqs: [["空行にも追加されますか？", "はい。入力に含まれる各行をそのまま対象にします。"], privacyFaq],
  },
  {
    id: "line-numbers", mode: "line-numbers", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/line-numbers/", name: "行番号追加・削除",
    title: "行番号追加・削除｜複数行テキストを一括処理",
    description: "テキストの各行に連番を付けたり、先頭の行番号らしき部分をまとめて削除します。",
    faqs: [["どんな形式で番号が付きますか？", "1. から始まる連番を各行の先頭に追加します。"], privacyFaq],
  },
  {
    id: "remove-empty-lines", mode: "remove-empty-lines", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/remove-empty-lines/", name: "空行削除",
    title: "空行削除ツール｜空白だけの行も一括削除",
    description: "空行と空白文字だけの行を削除し、内容のある行だけを残します。",
    faqs: [["スペースだけの行も削除されますか？", "はい。trim後に空になる行を削除します。"], privacyFaq],
  },
  {
    id: "tabs-spaces", mode: "tabs-spaces", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/tabs-spaces/", name: "タブ ⇔ スペース変換",
    title: "タブ・スペース変換｜インデント幅を指定",
    description: "タブを指定数のスペースへ、または連続スペースをタブへ置換します。",
    faqs: [["スペース数は変更できますか？", "はい。1〜16文字の範囲で指定できます。"], privacyFaq],
  },
  {
    id: "sort-lines", mode: "sort-lines", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/sort-lines/", name: "行を並べ替え",
    title: "テキスト行ソート｜昇順・降順で一括並べ替え",
    description: "複数行テキストを昇順または降順で並べ替えます。大文字小文字の無視にも対応します。",
    faqs: [["日本語も並べ替えできますか？", "はい。ブラウザのロケール比較を使って並べ替えます。"], privacyFaq],
  },
  {
    id: "random-lines", mode: "random-lines", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/random-lines/", name: "ランダム行抽出",
    title: "ランダム行抽出｜複数行から指定件数を無作為抽出",
    description: "複数行のリストから指定した件数をランダムに抽出します。",
    faqs: [["同じ行が重複して選ばれますか？", "入力上の各行を1回ずつシャッフルするため、同じ位置の行は重複抽出しません。"], privacyFaq],
  },
  {
    id: "case-converter", mode: "case-converter", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/case-converter/", name: "大文字・小文字変換",
    title: "大文字・小文字変換｜UPPER・lower・Title変換",
    description: "英字の大文字、小文字、単語先頭大文字、大小反転をまとめて変換します。",
    faqs: [["日本語は変わりますか？", "日本語部分はそのままで、主に英字が変換対象です。"], privacyFaq],
  },
  {
    id: "trim-lines", mode: "trim-lines", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/trim-lines/", name: "各行の前後空白削除",
    title: "各行の前後空白削除｜行ごとにtrim",
    description: "各行の先頭・末尾にある余分なスペースやタブを一括で削除します。",
    faqs: [["行の途中のスペースも消えますか？", "いいえ。各行の先頭と末尾だけを対象にします。"], privacyFaq],
  },
  {
    id: "json-key-list", mode: "json-key-list", family: "utilityplus", category: "JSON", categoryKey: "json",
    href: "/json/key-list/", name: "JSONキー一覧抽出",
    title: "JSONキー一覧抽出｜ネストしたキーもパス表示",
    description: "JSON内のキーを再帰的にたどり、ネストした項目もドット区切りのパスで一覧化します。",
    faqs: [["配列の中のオブジェクトも対象ですか？", "はい。配列要素内のオブジェクトも再帰的に確認します。"], privacyFaq],
  },
  {
    id: "json-sort-keys", mode: "json-sort-keys", family: "utilityplus", category: "JSON", categoryKey: "json",
    href: "/json/sort-keys/", name: "JSONキー並べ替え",
    title: "JSONキー並べ替え｜キー名順に再帰ソート",
    description: "JSONオブジェクトのキーを階層ごとに名前順で並べ替えて整形します。",
    faqs: [["ネストしたJSONも並べ替わりますか？", "はい。オブジェクトを再帰的に処理します。"], privacyFaq],
  },
  {
    id: "json-flatten", mode: "json-flatten", family: "utilityplus", category: "JSON", categoryKey: "json",
    href: "/json/flatten/", name: "JSONフラット化",
    title: "JSONフラット化｜ネストをドット区切りキーへ変換",
    description: "ネストしたJSONを user.name のようなフラットなキーへ展開します。",
    faqs: [["配列も展開されますか？", "はい。配列インデックスもキーの一部として展開します。"], privacyFaq],
  },
  {
    id: "json-typescript", mode: "json-typescript", family: "utilityplus", category: "JSON", categoryKey: "json",
    href: "/json/to-typescript/", name: "JSON → TypeScript型",
    title: "JSONからTypeScript型を生成｜簡易型推論",
    description: "JSONサンプルからTypeScriptの型定義を簡易生成します。",
    faqs: [["配列の型はどう決まりますか？", "先頭要素をもとに簡易推論します。厳密なスキーマ生成ではありません。"], privacyFaq],
  },
  {
    id: "regex-tester", mode: "regex-tester", family: "utilityplus", category: "開発者", categoryKey: "developer",
    href: "/developer/regex-tester/", name: "正規表現テスター",
    title: "正規表現テスター｜JavaScript RegExpをブラウザで確認",
    description: "正規表現パターンとフラグを指定し、入力テキストに対する一致内容と位置を確認します。",
    faqs: [["どの正規表現仕様ですか？", "ブラウザのJavaScript RegExpを利用します。"], privacyFaq],
  },
  {
    id: "random-string", mode: "random-string", family: "utilityplus", category: "開発者", categoryKey: "developer",
    href: "/developer/random-string/", name: "ランダム文字列生成",
    title: "ランダム文字列生成｜英数字をまとめて作成",
    description: "暗号学的乱数を使い、指定文字数・指定件数の英数字文字列を生成します。",
    faqs: [["乱数には何を使いますか？", "ブラウザのcrypto.getRandomValuesを利用します。"], privacyFaq],
  },
  {
    id: "password-generator", mode: "password-generator", family: "utilityplus", category: "開発者", categoryKey: "developer",
    href: "/developer/password-generator/", name: "パスワード生成",
    title: "パスワード生成｜長さ・記号有無を指定",
    description: "紛らわしい文字を避けつつ、暗号学的乱数でランダムなパスワードをまとめて生成します。",
    faqs: [["生成したパスワードは送信されますか？", "いいえ。すべてブラウザ内で生成します。"], privacyFaq],
  },
  {
    id: "sql-values", mode: "sql-values", family: "utilityplus", category: "開発者", categoryKey: "developer",
    href: "/developer/sql-values/", name: "SQL VALUES句生成",
    title: "SQL VALUES句生成｜値の一覧から複数行タプル作成",
    description: "改行・カンマ区切りの値を指定列数ごとにまとめ、SQL VALUESへ貼れるタプルを生成します。",
    faqs: [["シングルクォートはどう処理しますか？", "SQL文字列として扱えるよう内部のシングルクォートを二重化します。"], privacyFaq],
  },
  {
    id: "slug", mode: "slug", family: "utilityplus", category: "開発者", categoryKey: "developer",
    href: "/developer/slug/", name: "URLスラッグ生成",
    title: "URLスラッグ生成｜英数字をハイフン・アンダースコア化",
    description: "英数字テキストを小文字化し、URL向けのシンプルなスラッグへ変換します。",
    faqs: [["日本語もローマ字になりますか？", "いいえ。現在は英数字中心の簡易変換です。"], privacyFaq],
  },
  {
    id: "url-parts", mode: "url-parts", family: "utilityplus", category: "開発者", categoryKey: "developer",
    href: "/developer/url-parts/", name: "URL分解",
    title: "URL分解ツール｜host・path・query・hashを確認",
    description: "URLをprotocol、host、pathname、query、hashなどの構成要素へ分解します。",
    faqs: [["クエリパラメータも見られますか？", "はい。queryをJSONオブジェクトとして表示します。"], privacyFaq],
  },
  {
    id: "date-difference", mode: "date-difference", family: "utilityplus", category: "日付", categoryKey: "date",
    href: "/date/difference/", name: "日数差計算",
    title: "日数差計算｜2つの日付の差をブラウザで計算",
    description: "開始日と終了日を指定し、2つの日付の差を日数で計算します。",
    faqs: [["終了日が開始日より前でも使えますか？", "はい。符号付きの日数差と絶対値の両方を表示します。"], privacyFaq],
  },
  {
    id: "age", mode: "age", family: "utilityplus", category: "日付", categoryKey: "date",
    href: "/date/age/", name: "年齢計算",
    title: "年齢計算｜生年月日と基準日から満年齢を計算",
    description: "生年月日と基準日を指定し、その日時点の満年齢を計算します。",
    faqs: [["今日以外の時点も計算できますか？", "はい。基準日を自由に変更できます。"], privacyFaq],
  },
  {
    id: "date-add", mode: "date-add", family: "utilityplus", category: "日付", categoryKey: "date",
    href: "/date/add-subtract/", name: "日付の加算・減算",
    title: "日付の加算・減算｜指定日からN日後・N日前を計算",
    description: "基準日に日数を足したり引いたりして、N日後・N日前の日付を求めます。",
    faqs: [["過去の日付も計算できますか？", "はい。負の数を入力すると日付を減算できます。"], privacyFaq],
  },
  {
    id: "business-days", mode: "business-days", family: "utilityplus", category: "日付", categoryKey: "date",
    href: "/date/business-days/", name: "平日数・営業日数計算",
    title: "平日数計算｜土日を除いた日数を計算",
    description: "開始日から終了日までのうち、土曜日と日曜日を除いた日数を数えます。",
    faqs: [["祝日は除外されますか？", "いいえ。現在は土日のみを除外し、祝日は平日として数えます。"], privacyFaq],
  },
  {
    id: "percent-change", mode: "percent-change", family: "utilityplus", category: "計算", categoryKey: "calculator",
    href: "/calculator/percent-change/", name: "増減率・何％増減計算",
    title: "増減率計算｜変更前から何％増えた・減ったを計算",
    description: "変更前と変更後の数値から、増減率をパーセントで計算します。",
    faqs: [["減少した場合も計算できますか？", "はい。減少の場合はマイナスのパーセントで表示します。"], privacyFaq],
  },
  {
    id: "ratio", mode: "ratio", family: "utilityplus", category: "計算", categoryKey: "calculator",
    href: "/calculator/ratio/", name: "比率計算",
    title: "比率計算｜2つの値をA:B形式に簡約",
    description: "2つの数値の比率を簡約し、A:B形式とA÷Bの値を表示します。",
    faqs: [["小数にも対応しますか？", "はい。小数は一定精度で整数化して比率を簡約します。"], privacyFaq],
  },
  {
    id: "video-compress", mode: "compress", family: "video", category: "動画", categoryKey: "video",
    href: "/video/compress/", name: "動画圧縮",
    title: "動画圧縮ツール｜MP4をブラウザ内で軽量化",
    description: "動画をブラウザ内で再エンコードし、画質を選びながらファイル容量を小さくします。",
    faqs: [["どのくらい圧縮できますか？", "元動画や選択した圧縮レベルによって変わります。標準では画質と容量のバランスを取って圧縮します。"], ["動画はサーバーへ送信されますか？", "いいえ。動画ファイル自体は送信せず、ブラウザ内のFFmpegで処理します。"]],
  },
  {
    id: "video-to-mp3", mode: "to-mp3", family: "video", category: "動画", categoryKey: "video",
    href: "/video/to-mp3/", name: "動画 → MP3変換",
    title: "動画をMP3に変換｜音声をブラウザ内で抽出",
    description: "動画ファイルから音声を抽出し、128〜320kbpsのMP3として保存します。",
    faqs: [["音質は選べますか？", "はい。128、192、256、320kbpsから選択できます。"], ["動画はサーバーへ送信されますか？", "いいえ。動画ファイル自体は送信せず、ブラウザ内のFFmpegで処理します。"]],
  },
  {
    id: "pdf-merge", mode: "merge", family: "pdf", category: "PDF", categoryKey: "pdf",
    href: "/pdf/merge/", name: "PDF結合",
    title: "PDF結合ツール｜複数PDFを無料で1つに",
    description: "複数のPDFを選択順に結合し、1つのPDFとして保存します。",
    faqs: [["PDFはアップロードされますか？", "いいえ。PDFの読み込みと結合はブラウザ内で処理します。"], privacyFaq],
  },
  {
    id: "pdf-split", mode: "split", family: "pdf", category: "PDF", categoryKey: "pdf",
    href: "/pdf/split/", name: "PDF分割・ページ抽出",
    title: "PDF分割・ページ抽出｜ページ範囲を指定",
    description: "PDFのページ範囲を指定し、複数PDFへ分割してZIPで保存します。",
    faqs: [["ページ範囲はどう指定しますか？", "1-3,4-6,8 のようにカンマ区切りで指定できます。"], privacyFaq],
  },  {
    id: "pdf-to-images", mode: "to-images", family: "pdf", category: "PDF", categoryKey: "pdf",
    href: "/pdf/to-images/", name: "PDF → PNG画像変換",
    title: "PDFをPNG画像に変換｜ページごとに保存",
    description: "PDF各ページをPNG画像へ変換し、ZIPでまとめて保存します。",
    faqs: [["複数ページも変換できますか？", "はい。全ページを順番にPNG化します。"], privacyFaq],
  },
  {
    id: "qr-generate", mode: "generate", family: "qr", category: "QRコード", categoryKey: "qr",
    href: "/qr/generate/", name: "QRコード生成",
    title: "QRコード生成｜URL・テキストから無料作成",
    description: "URLやテキストからQRコードを生成し、PNGで保存できます。",
    faqs: [["日本語もQRコードにできますか？", "はい。日本語を含むテキストにも対応します。"], privacyFaq],
  },
  {
    id: "qr-read", mode: "read", family: "qr", category: "QRコード", categoryKey: "qr",
    href: "/qr/read/", name: "QRコード読み取り",
    title: "QRコード読み取り｜画像から内容を解析",
    description: "QRコード画像を選択し、ブラウザ内で内容を読み取ります。",
    faqs: [["撮影済みの画像から読み取れますか？", "はい。PNG・JPG・WebP画像を選択できます。"], privacyFaq],
  },
  {
    id: "uuid-generator", mode: "uuid", family: "developer", category: "開発者", categoryKey: "developer",
    href: "/developer/uuid/", name: "UUID生成",
    title: "UUID v4生成ツール｜まとめて無料生成",
    description: "ブラウザの暗号学的乱数を使ってUUID v4をまとめて生成します。",
    faqs: [["UUID v4ですか？", "はい。crypto.randomUUID()を利用してUUID v4を生成します。"], privacyFaq],
  },
  {
    id: "unix-time", mode: "unix-time", family: "developer", category: "開発者", categoryKey: "developer",
    href: "/developer/unix-time/", name: "Unix時間変換",
    title: "Unix時間・日時変換｜秒・ミリ秒対応",
    description: "Unixタイムスタンプと日時を相互変換します。秒・ミリ秒を自動判定します。",
    faqs: [["秒とミリ秒の両方に対応しますか？", "はい。桁数をもとに自動判定します。"], privacyFaq],
  },
];

export const extraToolByPath = new Map(extraTools.map((tool) => [tool.href, tool]));
