export type ExtraToolFamily = "image" | "csv" | "text" | "pdf" | "qr" | "video" | "developer" | "utility" | "utilityplus" | "csvmore" | "generalmore";
export type ExtraToolCategory = "image" | "csv" | "json" | "text" | "pdf" | "qr" | "video" | "japanese" | "developer" | "date" | "calculator";

export type ExtraToolMeta = {
  id: string;
  mode: string;
  family: ExtraToolFamily;
  category: string;
  categoryKey: ExtraToolCategory;
  href: string;
  name: string;
  title: string;
  description: string;
  faqs: readonly (readonly [string, string])[];
};

const privacyFaq = ["入力したデータはサーバーに送信されますか？", "いいえ。このツールの処理はブラウザ内で完結します。"] as const;

export const extraTools: ExtraToolMeta[] = [
  {
    id: "image-compress", mode: "compress", family: "image", category: "画像", categoryKey: "image",
    href: "/image/compress/", name: "画像圧縮",
    title: "画像圧縮ツール｜JPG・PNG・WebPを無料で圧縮",
    description: "JPG・PNG・WebP画像をブラウザ内で圧縮し、容量を小さくします。",
    faqs: [["画質は調整できますか？", "はい。品質スライダーで圧縮率を調整できます。"], privacyFaq],
  },
  {
    id: "image-resize", mode: "resize", family: "image", category: "画像", categoryKey: "image",
    href: "/image/resize/", name: "画像サイズ変更",
    title: "画像サイズ変更ツール｜幅・高さを無料でリサイズ",
    description: "画像の幅・高さを指定してリサイズします。縦横比の維持にも対応します。",
    faqs: [["縦横比を維持できますか？", "はい。縦横比を維持したまま幅または高さを基準に変更できます。"], privacyFaq],
  },
  {
    id: "png-to-jpg", mode: "png-to-jpg", family: "image", category: "画像", categoryKey: "image",
    href: "/image/png-to-jpg/", name: "PNG → JPG変換",
    title: "PNGをJPGに変換｜無料・ブラウザ内処理",
    description: "PNG画像をJPEGへ変換します。透明部分の背景色も指定できます。",
    faqs: [["透明部分はどうなりますか？", "指定した背景色で塗りつぶしてJPEGへ変換します。"], privacyFaq],
  },
  {
    id: "webp-converter", mode: "webp-converter", family: "image", category: "画像", categoryKey: "image",
    href: "/image/webp-converter/", name: "WebP → JPG・PNG変換",
    title: "WebPをJPG・PNGに変換｜無料",
    description: "WebP画像をJPGまたはPNGへ変換します。",
    faqs: [["JPGとPNGのどちらに変換できますか？", "どちらも選択できます。"], privacyFaq],
  },  {
    id: "image-crop", mode: "crop", family: "image", category: "画像", categoryKey: "image",
    href: "/image/crop/", name: "画像トリミング",
    title: "画像トリミングツール｜範囲指定で切り抜き",
    description: "画像のX・Y座標と幅・高さを指定して切り抜きます。",
    faqs: [["切り抜く範囲は数値指定できますか？", "はい。開始位置と幅・高さをピクセル単位で指定できます。"], privacyFaq],
  },
  {
    id: "target-filesize", mode: "target-filesize", family: "image", category: "画像", categoryKey: "image",
    href: "/image/target-filesize/", name: "画像を指定容量以下に圧縮",
    title: "画像を500KB・1MB以下に圧縮｜容量指定",
    description: "目標容量をKBで指定し、JPEGまたはWebPの品質を自動調整します。",
    faqs: [["必ず指定容量以下になりますか？", "品質を下げても到達できない場合は、その時点で最小に近い結果を表示します。"], privacyFaq],
  },
  {
    id: "csv-merge", mode: "merge", family: "csv", category: "CSV", categoryKey: "csv",
    href: "/csv/merge/", name: "CSV結合",
    title: "CSV結合ツール｜複数CSVを1つにまとめる",
    description: "複数のCSVファイルを読み込み、列名を合わせて1つのCSVに結合します。",
    faqs: [["列の順番が違っても結合できますか？", "はい。ヘッダー名を基準に列を合わせます。"], privacyFaq],
  },
  {
    id: "csv-columns", mode: "columns", family: "csv", category: "CSV", categoryKey: "csv",
    href: "/csv/columns/", name: "CSV列削除・並べ替え",
    title: "CSVの列を削除・並べ替え｜無料",
    description: "CSVの列名を指定して、必要な列だけを好きな順番で出力します。",
    faqs: [["列の並べ替え方は？", "読み込み後に表示される列名をカンマ区切りで並べ直します。"], privacyFaq],
  },  {
    id: "csv-encoding", mode: "encoding", family: "csv", category: "CSV", categoryKey: "csv",
    href: "/csv/encoding/", name: "CSV文字コード変換",
    title: "CSV文字コード変換｜UTF-8・Shift_JIS対応",
    description: "CSVをUTF-8、BOM付きUTF-8、Shift_JISへブラウザ内で変換します。",
    faqs: [["Shift_JISに対応していますか？", "はい。UTF-8系とShift_JISの相互変換に対応します。"], privacyFaq],
  },
  {
    id: "csv-json", mode: "csv-json", family: "csv", category: "CSV・JSON", categoryKey: "csv",
    href: "/csv/json-converter/", name: "CSV ⇔ JSON変換",
    title: "CSVとJSONを相互変換｜無料",
    description: "CSVをJSONへ、JSON配列をCSVへ相互変換します。",
    faqs: [["JSONはどんな形式に対応しますか？", "オブジェクトの配列をCSVへ変換できます。"], privacyFaq],
  },
  {
    id: "json-formatter", mode: "json-formatter", family: "text", category: "テキスト", categoryKey: "text",
    href: "/text/json-formatter/", name: "JSON整形・圧縮・構文チェック",
    title: "JSON整形・圧縮・構文チェック｜無料",
    description: "JSONを読みやすく整形、1行に圧縮、構文エラーを確認できます。",
    faqs: [["JSONのエラーも分かりますか？", "はい。JSON.parseで検出した構文エラーを表示します。"], privacyFaq],
  },
  {
    id: "character-count", mode: "character-count", family: "text", category: "テキスト", categoryKey: "text",
    href: "/text/character-count/", name: "文字数カウント",
    title: "文字数カウント｜文字・行・バイト数を即時計測",
    description: "入力テキストの文字数、空白除外文字数、行数、UTF-8バイト数を数えます。",
    faqs: [["改行も文字数に含まれますか？", "通常の文字数には含まれます。行数は別に表示します。"], privacyFaq],
  },  {
    id: "fullwidth-halfwidth", mode: "fullwidth-halfwidth", family: "text", category: "テキスト", categoryKey: "text",
    href: "/text/fullwidth-halfwidth/", name: "全角・半角変換",
    title: "全角・半角変換｜英数字・スペースを一括変換",
    description: "英数字・記号・スペースを全角または半角へ一括変換します。",
    faqs: [["日本語の漢字やひらがなも変わりますか？", "いいえ。主にASCII範囲の英数字・記号とスペースを対象にします。"], privacyFaq],
  },
  {
    id: "newline-converter", mode: "newline-converter", family: "text", category: "テキスト", categoryKey: "text",
    href: "/text/newline-converter/", name: "改行削除・置換",
    title: "改行削除・置換ツール｜空白・カンマへ一括変換",
    description: "改行を削除したり、空白・カンマ・任意文字列へ置換します。",
    faqs: [["CRLFとLFの両方に対応しますか？", "はい。Windows・Unix系の改行をまとめて処理します。"], privacyFaq],
  },
  {
    id: "csv-duplicates", mode: "csv-duplicates", family: "utility", category: "CSV", categoryKey: "csv",
    href: "/csv/find-duplicates/", name: "CSV重複行検出",
    title: "CSV重複行検出｜重複レコードをブラウザ内で確認",
    description: "CSV内で完全一致する重複行を検出し、重複回数付きで一覧化します。",
    faqs: [["何を重複と判定しますか？", "すべての列の値が一致する行を重複として判定します。"], privacyFaq],
  },
  {
    id: "csv-remove-empty", mode: "csv-remove-empty", family: "utility", category: "CSV", categoryKey: "csv",
    href: "/csv/remove-empty-rows/", name: "CSV空行削除",
    title: "CSV空行削除｜空のレコードを無料で一括削除",
    description: "CSVを正しく解析し、すべての列が空の行だけを削除して保存します。",
    faqs: [["ヘッダーは残りますか？", "はい。先頭行はヘッダーとしてそのまま残します。"], privacyFaq],
  },
  {
    id: "csv-tsv", mode: "csv-tsv", family: "utility", category: "CSV", categoryKey: "csv",
    href: "/csv/tsv-converter/", name: "CSV ⇔ TSV変換",
    title: "CSVとTSVを相互変換｜タブ区切り・カンマ区切り",
    description: "CSVをTSVへ、TSVをCSVへ相互変換し、ファイルとして保存できます。",
    faqs: [["引用符付きの値にも対応しますか？", "はい。CSV/TSVパーサーで区切り文字や引用符を解析します。"], privacyFaq],
  },
  {
    id: "jsonl-json", mode: "jsonl-json", family: "utility", category: "JSON", categoryKey: "json",
    href: "/json/jsonl-converter/", name: "JSON Lines ⇔ JSON変換",
    title: "JSON LinesとJSON配列を相互変換｜JSONL変換",
    description: "1行1JSONのJSON Linesと通常のJSON配列を相互変換します。",
    faqs: [["JSON Linesとは何ですか？", "1行ごとに独立したJSONオブジェクトを記述する形式です。"], privacyFaq],
  },
  {
    id: "invisible-chars", mode: "invisible-chars", family: "utility", category: "テキスト", categoryKey: "text",
    href: "/text/invisible-characters/", name: "不可視文字検出",
    title: "不可視文字検出｜ゼロ幅スペース・NBSP・タブを確認",
    description: "テキスト内のゼロ幅スペース、NBSP、タブ、改行など見えにくい文字を位置付きで検出します。",
    faqs: [["どんな文字を検出しますか？", "ゼロ幅スペース、各種空白、タブ、改行、BOMなどを検出します。"], privacyFaq],
  },
  {
    id: "unicode-normalize", mode: "unicode-normalize", family: "utility", category: "テキスト", categoryKey: "text",
    href: "/text/unicode-normalize/", name: "Unicode正規化",
    title: "Unicode正規化｜NFC・NFKC・NFD・NFKD変換",
    description: "Unicode文字列をNFC、NFKC、NFD、NFKDの各形式へ正規化します。",
    faqs: [["NFKCは何に使えますか？", "互換文字をまとめたい場合などに利用できます。"], privacyFaq],
  },
  {
    id: "kana-converter", mode: "kana-converter", family: "utility", category: "日本語", categoryKey: "japanese",
    href: "/japanese/hiragana-katakana/", name: "ひらがな ⇔ カタカナ変換",
    title: "ひらがな・カタカナ変換｜相互変換ツール",
    description: "ひらがなをカタカナへ、カタカナをひらがなへ一括変換します。",
    faqs: [["漢字も変換されますか？", "いいえ。ひらがな・カタカナ部分だけを変換します。"], privacyFaq],
  },
  {
    id: "wareki", mode: "wareki", family: "utility", category: "日本語", categoryKey: "japanese",
    href: "/japanese/wareki/", name: "西暦 ⇔ 和暦変換",
    title: "西暦・和暦変換｜令和・平成・昭和・大正・明治",
    description: "西暦の日付と令和・平成・昭和・大正・明治の和暦を相互変換します。",
    faqs: [["どの元号に対応しますか？", "明治以降の主要元号に対応しています。"], privacyFaq],
  },
  {
    id: "base64", mode: "base64", family: "utility", category: "開発者", categoryKey: "developer",
    href: "/developer/base64/", name: "Base64エンコード・デコード",
    title: "Base64エンコード・デコード｜UTF-8対応",
    description: "日本語を含むUTF-8テキストをBase64へエンコード・デコードします。",
    faqs: [["日本語にも対応しますか？", "はい。UTF-8として安全に変換します。"], privacyFaq],
  },
  {
    id: "url-codec", mode: "url-codec", family: "utility", category: "開発者", categoryKey: "developer",
    href: "/developer/url-encode/", name: "URLエンコード・デコード",
    title: "URLエンコード・デコード｜パーセントエンコーディング",
    description: "URLに含める文字列をencodeURIComponent互換でエンコード・デコードします。",
    faqs: [["スペースや日本語も変換できますか？", "はい。URLコンポーネント向けに変換します。"], privacyFaq],
  },
  {
    id: "html-codec", mode: "html-codec", family: "utility", category: "開発者", categoryKey: "developer",
    href: "/developer/html-escape/", name: "HTMLエスケープ・解除",
    title: "HTMLエスケープ・アンエスケープ｜特殊文字変換",
    description: "HTMLの &, <, >, 引用符などを安全な文字参照へ変換・復元します。",
    faqs: [["どの文字をエスケープしますか？", "&、<、>、ダブルクォート、シングルクォートを変換します。"], privacyFaq],
  },
  {
    id: "sha", mode: "sha", family: "utility", category: "開発者", categoryKey: "developer",
    href: "/developer/sha/", name: "SHA-256・SHA-512生成",
    title: "SHA-256・SHA-512ハッシュ生成｜ブラウザ内計算",
    description: "入力テキストからSHA-256またはSHA-512のハッシュ値を生成します。",
    faqs: [["パスワード保存用ですか？", "単純なSHAハッシュ生成です。パスワード保存には専用のパスワードハッシュ方式を利用してください。"], privacyFaq],
  },
  {
    id: "file-sha", mode: "file-sha", family: "utility", category: "開発者", categoryKey: "developer",
    href: "/developer/file-hash/", name: "ファイルSHA-256・SHA-512計算",
    title: "ファイルSHA-256・SHA-512計算｜ハッシュ値確認",
    description: "選択したファイルのSHA-256またはSHA-512をブラウザ内で計算します。",
    faqs: [["ファイルはアップロードされますか？", "いいえ。ファイル内容はブラウザ内だけで読み込み、ハッシュを計算します。"], privacyFaq],
  },
  {
    id: "jwt-decode", mode: "jwt-decode", family: "utility", category: "開発者", categoryKey: "developer",
    href: "/developer/jwt-decode/", name: "JWTデコード",
    title: "JWTデコード｜Header・Payloadをブラウザ内で確認",
    description: "JWTのHeaderとPayloadをデコードして読みやすいJSONで表示します。",
    faqs: [["署名も検証できますか？", "いいえ。このツールは内容のデコードのみで、署名の正当性は検証しません。"], privacyFaq],
  },
  {
    id: "sql-in", mode: "sql-in", family: "utility", category: "開発者", categoryKey: "developer",
    href: "/developer/sql-in/", name: "SQL IN句生成",
    title: "SQL IN句生成｜改行・カンマ区切りから一括作成",
    description: "値の一覧からSQLのIN句に貼り付けられる形式を生成します。文字列のクォートも自動処理します。",
    faqs: [["シングルクォートを含む値はどうなりますか？", "SQL文字列として扱えるようシングルクォートを二重化します。"], privacyFaq],
  },
  {
    id: "line-prefix-suffix", mode: "line-prefix-suffix", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/line-prefix-suffix/", name: "各行の行頭・行末に文字追加",
    title: "各行の行頭・行末に文字を一括追加｜テキスト整形",
    description: "複数行テキストの各行へ、指定した接頭辞と接尾辞をまとめて追加します。",
    faqs: [["空行にも追加されますか？", "はい。入力に含まれる各行をそのまま対象にします。"], privacyFaq],
  },
  {
    id: "line-numbers", mode: "line-numbers", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/line-numbers/", name: "行番号追加・削除",
    title: "行番号追加・削除｜複数行テキストを一括処理",
    description: "テキストの各行に連番を付けたり、先頭の行番号らしき部分をまとめて削除します。",
    faqs: [["どんな形式で番号が付きますか？", "1. から始まる連番を各行の先頭に追加します。"], privacyFaq],
  },
  {
    id: "remove-empty-lines", mode: "remove-empty-lines", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/remove-empty-lines/", name: "空行削除",
    title: "空行削除ツール｜空白だけの行も一括削除",
    description: "空行と空白文字だけの行を削除し、内容のある行だけを残します。",
    faqs: [["スペースだけの行も削除されますか？", "はい。trim後に空になる行を削除します。"], privacyFaq],
  },
  {
    id: "tabs-spaces", mode: "tabs-spaces", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/tabs-spaces/", name: "タブ ⇔ スペース変換",
    title: "タブ・スペース変換｜インデント幅を指定",
    description: "タブを指定数のスペースへ、または連続スペースをタブへ置換します。",
    faqs: [["スペース数は変更できますか？", "はい。1〜16文字の範囲で指定できます。"], privacyFaq],
  },
  {
    id: "sort-lines", mode: "sort-lines", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/sort-lines/", name: "行を並べ替え",
    title: "テキスト行ソート｜昇順・降順で一括並べ替え",
    description: "複数行テキストを昇順または降順で並べ替えます。大文字小文字の無視にも対応します。",
    faqs: [["日本語も並べ替えできますか？", "はい。ブラウザのロケール比較を使って並べ替えます。"], privacyFaq],
  },
  {
    id: "random-lines", mode: "random-lines", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/random-lines/", name: "ランダム行抽出",
    title: "ランダム行抽出｜複数行から指定件数を無作為抽出",
    description: "複数行のリストから指定した件数をランダムに抽出します。",
    faqs: [["同じ行が重複して選ばれますか？", "入力上の各行を1回ずつシャッフルするため、同じ位置の行は重複抽出しません。"], privacyFaq],
  },
  {
    id: "case-converter", mode: "case-converter", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/case-converter/", name: "大文字・小文字変換",
    title: "大文字・小文字変換｜UPPER・lower・Title変換",
    description: "英字の大文字、小文字、単語先頭大文字、大小反転をまとめて変換します。",
    faqs: [["日本語は変わりますか？", "日本語部分はそのままで、主に英字が変換対象です。"], privacyFaq],
  },
  {
    id: "trim-lines", mode: "trim-lines", family: "utilityplus", category: "テキスト", categoryKey: "text",
    href: "/text/trim-lines/", name: "各行の前後空白削除",
    title: "各行の前後空白削除｜行ごとにtrim",
    description: "各行の先頭・末尾にある余分なスペースやタブを一括で削除します。",
    faqs: [["行の途中のスペースも消えますか？", "いいえ。各行の先頭と末尾だけを対象にします。"], privacyFaq],
  },
  {
    id: "json-key-list", mode: "json-key-list", family: "utilityplus", category: "JSON", categoryKey: "json",
    href: "/json/key-list/", name: "JSONキー一覧抽出",
    title: "JSONキー一覧抽出｜ネストしたキーもパス表示",
    description: "JSON内のキーを再帰的にたどり、ネストした項目もドット区切りのパスで一覧化します。",
    faqs: [["配列の中のオブジェクトも対象ですか？", "はい。配列要素内のオブジェクトも再帰的に確認します。"], privacyFaq],
  },
  {
    id: "json-sort-keys", mode: "json-sort-keys", family: "utilityplus", category: "JSON", categoryKey: "json",
    href: "/json/sort-keys/", name: "JSONキー並べ替え",
    title: "JSONキー並べ替え｜キー名順に再帰ソート",
    description: "JSONオブジェクトのキーを階層ごとに名前順で並べ替えて整形します。",
    faqs: [["ネストしたJSONも並べ替わりますか？", "はい。オブジェクトを再帰的に処理します。"], privacyFaq],
  },
  {
    id: "json-flatten", mode: "json-flatten", family: "utilityplus", category: "JSON", categoryKey: "json",
    href: "/json/flatten/", name: "JSONフラット化",
    title: "JSONフラット化｜ネストをドット区切りキーへ変換",
    description: "ネストしたJSONを user.name のようなフラットなキーへ展開します。",
    faqs: [["配列も展開されますか？", "はい。配列インデックスもキーの一部として展開します。"], privacyFaq],
  },
  {
    id: "json-typescript", mode: "json-typescript", family: "utilityplus", category: "JSON", categoryKey: "json",
    href: "/json/to-typescript/", name: "JSON → TypeScript型",
    title: "JSONからTypeScript型を生成｜簡易型推論",
    description: "JSONサンプルからTypeScriptの型定義を簡易生成します。",
    faqs: [["配列の型はどう決まりますか？", "先頭要素をもとに簡易推論します。厳密なスキーマ生成ではありません。"], privacyFaq],
  },
  {
    id: "regex-tester", mode: "regex-tester", family: "utilityplus", category: "開発者", categoryKey: "developer",
    href: "/developer/regex-tester/", name: "正規表現テスター",
    title: "正規表現テスター｜JavaScript RegExpをブラウザで確認",
    description: "正規表現パターンとフラグを指定し、入力テキストに対する一致内容と位置を確認します。",
    faqs: [["どの正規表現仕様ですか？", "ブラウザのJavaScript RegExpを利用します。"], privacyFaq],
  },
  {
    id: "random-string", mode: "random-string", family: "utilityplus", category: "開発者", categoryKey: "developer",
    href: "/developer/random-string/", name: "ランダム文字列生成",
    title: "ランダム文字列生成｜英数字をまとめて作成",
    description: "暗号学的乱数を使い、指定文字数・指定件数の英数字文字列を生成します。",
    faqs: [["乱数には何を使いますか？", "ブラウザのcrypto.getRandomValuesを利用します。"], privacyFaq],
  },
  {
    id: "password-generator", mode: "password-generator", family: "utilityplus", category: "開発者", categoryKey: "developer",
    href: "/developer/password-generator/", name: "パスワード生成",
    title: "パスワード生成｜長さ・記号有無を指定",
    description: "紛らわしい文字を避けつつ、暗号学的乱数でランダムなパスワードをまとめて生成します。",
    faqs: [["生成したパスワードは送信されますか？", "いいえ。すべてブラウザ内で生成します。"], privacyFaq],
  },
  {
    id: "sql-values", mode: "sql-values", family: "utilityplus", category: "開発者", categoryKey: "developer",
    href: "/developer/sql-values/", name: "SQL VALUES句生成",
    title: "SQL VALUES句生成｜値の一覧から複数行タプル作成",
    description: "改行・カンマ区切りの値を指定列数ごとにまとめ、SQL VALUESへ貼れるタプルを生成します。",
    faqs: [["シングルクォートはどう処理しますか？", "SQL文字列として扱えるよう内部のシングルクォートを二重化します。"], privacyFaq],
  },
  {
    id: "slug", mode: "slug", family: "utilityplus", category: "開発者", categoryKey: "developer",
    href: "/developer/slug/", name: "URLスラッグ生成",
    title: "URLスラッグ生成｜英数字をハイフン・アンダースコア化",
    description: "英数字テキストを小文字化し、URL向けのシンプルなスラッグへ変換します。",
    faqs: [["日本語もローマ字になりますか？", "いいえ。現在は英数字中心の簡易変換です。"], privacyFaq],
  },
  {
    id: "url-parts", mode: "url-parts", family: "utilityplus", category: "開発者", categoryKey: "developer",
    href: "/developer/url-parts/", name: "URL分解",
    title: "URL分解ツール｜host・path・query・hashを確認",
    description: "URLをprotocol、host、pathname、query、hashなどの構成要素へ分解します。",
    faqs: [["クエリパラメータも見られますか？", "はい。queryをJSONオブジェクトとして表示します。"], privacyFaq],
  },
  {
    id: "date-difference", mode: "date-difference", family: "utilityplus", category: "日付", categoryKey: "date",
    href: "/date/difference/", name: "日数差計算",
    title: "日数差計算｜2つの日付の差をブラウザで計算",
    description: "開始日と終了日を指定し、2つの日付の差を日数で計算します。",
    faqs: [["終了日が開始日より前でも使えますか？", "はい。符号付きの日数差と絶対値の両方を表示します。"], privacyFaq],
  },
  {
    id: "age", mode: "age", family: "utilityplus", category: "日付", categoryKey: "date",
    href: "/date/age/", name: "年齢計算",
    title: "年齢計算｜生年月日と基準日から満年齢を計算",
    description: "生年月日と基準日を指定し、その日時点の満年齢を計算します。",
    faqs: [["今日以外の時点も計算できますか？", "はい。基準日を自由に変更できます。"], privacyFaq],
  },
  {
    id: "date-add", mode: "date-add", family: "utilityplus", category: "日付", categoryKey: "date",
    href: "/date/add-subtract/", name: "日付の加算・減算",
    title: "日付の加算・減算｜指定日からN日後・N日前を計算",
    description: "基準日に日数を足したり引いたりして、N日後・N日前の日付を求めます。",
    faqs: [["過去の日付も計算できますか？", "はい。負の数を入力すると日付を減算できます。"], privacyFaq],
  },
  {
    id: "business-days", mode: "business-days", family: "utilityplus", category: "日付", categoryKey: "date",
    href: "/date/business-days/", name: "平日数・営業日数計算",
    title: "平日数計算｜土日を除いた日数を計算",
    description: "開始日から終了日までのうち、土曜日と日曜日を除いた日数を数えます。",
    faqs: [["祝日は除外されますか？", "いいえ。現在は土日のみを除外し、祝日は平日として数えます。"], privacyFaq],
  },
  {
    id: "percent-change", mode: "percent-change", family: "utilityplus", category: "計算", categoryKey: "calculator",
    href: "/calculator/percent-change/", name: "増減率・何％増減計算",
    title: "増減率計算｜変更前から何％増えた・減ったを計算",
    description: "変更前と変更後の数値から、増減率をパーセントで計算します。",
    faqs: [["減少した場合も計算できますか？", "はい。減少の場合はマイナスのパーセントで表示します。"], privacyFaq],
  },
  {
    id: "ratio", mode: "ratio", family: "utilityplus", category: "計算", categoryKey: "calculator",
    href: "/calculator/ratio/", name: "比率計算",
    title: "比率計算｜2つの値をA:B形式に簡約",
    description: "2つの数値の比率を簡約し、A:B形式とA÷Bの値を表示します。",
    faqs: [["小数にも対応しますか？", "はい。小数は一定精度で整数化して比率を簡約します。"], privacyFaq],
  },
  {
    id: "csv-sort", mode: "csv-sort", family: "csvmore", category: "CSV", categoryKey: "csv",
    href: "/csv/sort/", name: "CSV列ソート",
    title: "CSV列ソート｜指定列で昇順・降順に並べ替え",
    description: "CSVの指定列を基準に、数値・文字列を昇順または降順で並べ替えます。",
    faqs: [["数値と文字列の両方に対応しますか？", "はい。数値として解釈できる値は数値順、それ以外は文字列順で並べます。"], privacyFaq],
  },
  {
    id: "csv-filter", mode: "csv-filter", family: "csvmore", category: "CSV", categoryKey: "csv",
    href: "/csv/filter/", name: "CSV行フィルター",
    title: "CSV行フィルター｜列と条件を指定して抽出",
    description: "列名と条件値を指定して、完全一致・部分一致・前方一致などでCSV行を抽出します。",
    faqs: [["どんな条件を使えますか？", "含む、完全一致、一致しない、前方一致、後方一致に対応します。"], privacyFaq],
  },
  {
    id: "csv-row-number", mode: "csv-row-number", family: "csvmore", category: "CSV", categoryKey: "csv",
    href: "/csv/add-row-number/", name: "CSV行番号追加",
    title: "CSV行番号追加｜連番列を先頭に追加",
    description: "CSVの先頭列へ1から始まる連番を追加します。列名も自由に変更できます。",
    faqs: [["ヘッダーも番号に含まれますか？", "いいえ。データ行だけに1から順番に番号を付けます。"], privacyFaq],
  },
  {
    id: "csv-rename-headers", mode: "csv-rename-headers", family: "csvmore", category: "CSV", categoryKey: "csv",
    href: "/csv/rename-headers/", name: "CSV列名一括変更",
    title: "CSV列名一括変更｜old=new形式でヘッダーを置換",
    description: "複数のCSVヘッダー名を old=new 形式のルールでまとめて変更します。",
    faqs: [["一部の列だけ変更できますか？", "はい。指定していない列名はそのまま残ります。"], privacyFaq],
  },
  {
    id: "csv-transpose", mode: "csv-transpose", family: "csvmore", category: "CSV", categoryKey: "csv",
    href: "/csv/transpose/", name: "CSV縦横入れ替え",
    title: "CSV縦横入れ替え｜行と列を転置",
    description: "CSVの行と列を入れ替えて、転置したCSVを作成します。",
    faqs: [["行ごとの列数が違っても使えますか？", "はい。足りないセルは空欄として補完します。"], privacyFaq],
  },
  {
    id: "csv-value-count", mode: "csv-value-count", family: "csvmore", category: "CSV", categoryKey: "csv",
    href: "/csv/value-count/", name: "CSV列の値を件数集計",
    title: "CSV値カウント｜指定列の値ごとに件数集計",
    description: "指定した列の値をグループ化し、出現回数の多い順に件数を集計します。",
    faqs: [["空欄も集計されますか？", "はい。空欄も1つの値として件数に含めます。"], privacyFaq],
  },
  {
    id: "json-array-dedupe", mode: "json-array-dedupe", family: "generalmore", category: "JSON", categoryKey: "json",
    href: "/json/array-dedupe/", name: "JSON配列の重複削除",
    title: "JSON配列の重複削除｜オブジェクト・値の重複を除去",
    description: "JSON配列内で内容が完全一致する要素を重複判定し、最初の1件だけ残します。",
    faqs: [["オブジェクト配列にも対応しますか？", "はい。JSON文字列化した内容が完全一致する要素を重複として扱います。"], privacyFaq],
  },
  {
    id: "json-array-sort", mode: "json-array-sort", family: "generalmore", category: "JSON", categoryKey: "json",
    href: "/json/array-sort/", name: "JSON配列ソート",
    title: "JSON配列ソート｜数値・文字列を昇順・降順に並べ替え",
    description: "文字列や数値などの単純なJSON配列を昇順・降順で並べ替えます。",
    faqs: [["オブジェクト配列も並べ替えできますか？", "このツールは単純な値の配列向けです。オブジェクト配列は対象外です。"], privacyFaq],
  },
  {
    id: "json-path", mode: "json-path", family: "generalmore", category: "JSON", categoryKey: "json",
    href: "/json/path-extractor/", name: "JSONパス抽出",
    title: "JSONパス抽出｜ドット区切りでネスト値を取得",
    description: "user.profile.name や items.0.id のようなドット区切りパスでJSON内の値を取り出します。",
    faqs: [["配列の要素も取得できますか？", "はい。items.0.name のように配列インデックスを指定できます。"], privacyFaq],
  },
  {
    id: "json-string-codec", mode: "json-string-codec", family: "generalmore", category: "JSON", categoryKey: "json",
    href: "/json/string-escape/", name: "JSON文字列エスケープ・復元",
    title: "JSON文字列エスケープ・アンエスケープ｜引用符・改行を変換",
    description: "通常のテキストをJSON文字列として安全にエスケープし、逆にJSON文字列を元のテキストへ戻します。",
    faqs: [["改行や引用符も処理されますか？", "はい。JSON.stringify / JSON.parse相当で処理します。"], privacyFaq],
  },
  {
    id: "find-replace", mode: "find-replace", family: "generalmore", category: "テキスト", categoryKey: "text",
    href: "/text/find-replace/", name: "文字列一括置換",
    title: "文字列一括置換｜検索文字列をすべて置換",
    description: "入力テキスト内の指定文字列を、別の文字列へ一括で置換します。",
    faqs: [["すべての一致箇所が置換されますか？", "はい。入力テキスト内の完全一致する検索文字列をすべて置換します。"], privacyFaq],
  },
  {
    id: "reverse-lines", mode: "reverse-lines", family: "generalmore", category: "テキスト", categoryKey: "text",
    href: "/text/reverse-lines/", name: "行順を逆転",
    title: "行順を逆転｜複数行テキストを上下反転",
    description: "複数行テキストの行順を最後から最初へ逆転します。",
    faqs: [["各行の文字列も逆になりますか？", "いいえ。行そのものの順番だけを逆転します。"], privacyFaq],
  },
  {
    id: "shuffle-lines", mode: "shuffle-lines", family: "generalmore", category: "テキスト", categoryKey: "text",
    href: "/text/shuffle-lines/", name: "行をランダム並べ替え",
    title: "行シャッフル｜複数行テキストをランダム並べ替え",
    description: "入力された行をブラウザ内の暗号学的乱数を使ってランダムに並べ替えます。",
    faqs: [["同じ内容の行は残りますか？", "はい。削除はせず、入力された行をそのまま並べ替えます。"], privacyFaq],
  },
  {
    id: "word-frequency", mode: "word-frequency", family: "generalmore", category: "テキスト", categoryKey: "text",
    href: "/text/word-frequency/", name: "単語出現回数カウント",
    title: "単語出現回数カウント｜頻出語を件数順に集計",
    description: "入力テキストを単語に分割し、出現回数の多い順に一覧表示します。",
    faqs: [["大文字と小文字は別扱いですか？", "いいえ。英字は小文字へ揃えて集計します。"], privacyFaq],
  },
  {
    id: "line-ending", mode: "line-ending", family: "generalmore", category: "テキスト", categoryKey: "text",
    href: "/text/line-ending/", name: "改行コード変換",
    title: "改行コード変換｜LF・CRLF・CRを相互変換",
    description: "テキストの改行コードをLF、CRLF、CRのいずれかへ統一します。",
    faqs: [["WindowsとLinuxの改行を変換できますか？", "はい。CRLFとLFを相互に変換できます。"], privacyFaq],
  },
  {
    id: "kana-normalize", mode: "kana-normalize", family: "generalmore", category: "日本語", categoryKey: "japanese",
    href: "/japanese/kana-normalize/", name: "半角カナ・全角文字正規化",
    title: "半角カナ・全角文字正規化｜NFKCで一括変換",
    description: "半角カタカナや全角英数字などをUnicode NFKCで標準的な表記へ正規化します。",
    faqs: [["半角カタカナも全角になりますか？", "はい。Unicode NFKC正規化により一般的な全角カタカナへ統一されます。"], privacyFaq],
  },
  {
    id: "punctuation-normalize", mode: "punctuation-normalize", family: "generalmore", category: "日本語", categoryKey: "japanese",
    href: "/japanese/punctuation-normalize/", name: "日本語記号の正規化",
    title: "日本語記号正規化｜句読点・括弧・記号を一括変換",
    description: "句読点や括弧などを、日本語寄りまたはASCII寄りの記号へまとめて変換します。",
    faqs: [["文章の文字自体も変わりますか？", "いいえ。対象となる句読点や一部の記号だけを変換します。"], privacyFaq],
  },
  {
    id: "space-normalize", mode: "space-normalize", family: "generalmore", category: "日本語", categoryKey: "japanese",
    href: "/japanese/space-normalize/", name: "日本語テキスト空白正規化",
    title: "空白正規化｜全角空白・連続スペースを一括整理",
    description: "全角空白を半角へ変換したり、連続空白を1つにまとめたり、空白をすべて削除します。",
    faqs: [["改行も削除されますか？", "空白をすべて削除するモードでは改行も空白として削除されます。"], privacyFaq],
  },
  {
    id: "japanese-char-count", mode: "japanese-char-count", family: "generalmore", category: "日本語", categoryKey: "japanese",
    href: "/japanese/character-types/", name: "日本語文字種カウント",
    title: "日本語文字種カウント｜ひらがな・カタカナ・漢字を集計",
    description: "入力テキストをひらがな、カタカナ、漢字、英字、数字、空白、その他に分けて件数を数えます。",
    faqs: [["半角カタカナも数えられますか？", "はい。半角カタカナもカタカナとして集計します。"], privacyFaq],
  },
  {
    id: "querystring", mode: "querystring", family: "generalmore", category: "開発者", categoryKey: "developer",
    href: "/developer/query-string/", name: "クエリ文字列 ⇔ JSON変換",
    title: "クエリ文字列とJSONを相互変換｜URLパラメータ変換",
    description: "a=1&b=2 のようなクエリ文字列をJSONへ、JSONオブジェクトをクエリ文字列へ変換します。",
    faqs: [["先頭の?は必要ですか？", "なくても使えます。付いている場合は自動で取り除きます。"], privacyFaq],
  },
  {
    id: "base-converter", mode: "base-converter", family: "generalmore", category: "開発者", categoryKey: "developer",
    href: "/developer/base-converter/", name: "基数変換 2〜36進数",
    title: "基数変換｜2進数・10進数・16進数などを相互変換",
    description: "2〜36進数の整数を、任意の別の基数へ変換します。",
    faqs: [["16進数のA〜Fにも対応しますか？", "はい。2〜36進数で英数字を使った表記に対応します。"], privacyFaq],
  },
  {
    id: "uuid-validate", mode: "uuid-validate", family: "generalmore", category: "開発者", categoryKey: "developer",
    href: "/developer/uuid-validate/", name: "UUID形式チェック",
    title: "UUID形式チェック｜UUIDバージョンも確認",
    description: "入力された文字列が一般的なUUID形式かを判定し、判定できる場合はバージョンも表示します。",
    faqs: [["UUID v4以外も判定できますか？", "はい。一般的なUUID形式を確認し、バージョン桁も表示します。"], privacyFaq],
  },
  {
    id: "ulid", mode: "ulid", family: "generalmore", category: "開発者", categoryKey: "developer",
    href: "/developer/ulid/", name: "ULID生成",
    title: "ULID生成｜時系列ソート可能なIDをまとめて作成",
    description: "現在時刻と暗号学的乱数を使って26文字のULID形式IDをまとめて生成します。",
    faqs: [["UUIDとの違いは何ですか？", "ULIDは先頭に時刻情報を含むため、文字列として時系列順に扱いやすい形式です。"], privacyFaq],
  },
  {
    id: "weekday", mode: "weekday", family: "generalmore", category: "日付", categoryKey: "date",
    href: "/date/weekday/", name: "曜日計算",
    title: "曜日計算｜指定日が何曜日か確認",
    description: "日付を指定して、日本語・英語の曜日をすぐに確認します。",
    faqs: [["過去や未来の日付にも対応しますか？", "はい。ブラウザで扱える日付範囲なら計算できます。"], privacyFaq],
  },
  {
    id: "iso-week", mode: "iso-week", family: "generalmore", category: "日付", categoryKey: "date",
    href: "/date/iso-week/", name: "ISO週番号計算",
    title: "ISO週番号計算｜指定日のISO weekを確認",
    description: "指定した日付がISO 8601の何年・第何週に属するかを計算します。",
    faqs: [["年末年始は翌年・前年の週になることがありますか？", "はい。ISO週番号のルールに従うため、暦年と週番号年が異なる場合があります。"], privacyFaq],
  },
  {
    id: "percentage", mode: "percentage", family: "generalmore", category: "計算", categoryKey: "calculator",
    href: "/calculator/percentage/", name: "何％か計算",
    title: "何％か計算｜AはBの何パーセントか",
    description: "ある値が全体の何％に当たるかを計算します。",
    faqs: [["小数にも対応しますか？", "はい。小数値でも計算できます。"], privacyFaq],
  },
  {
    id: "discount", mode: "discount", family: "generalmore", category: "計算", categoryKey: "calculator",
    href: "/calculator/discount/", name: "割引後価格計算",
    title: "割引計算｜○％OFF後の価格と値引額を計算",
    description: "元の価格と割引率から、割引後価格と値引額を計算します。",
    faqs: [["小数価格にも対応しますか？", "はい。小数も入力できます。"], privacyFaq],
  },
  {
    id: "stats", mode: "stats", family: "generalmore", category: "計算", categoryKey: "calculator",
    href: "/calculator/statistics/", name: "平均・中央値・標準偏差",
    title: "平均・中央値・標準偏差計算｜数値リストを集計",
    description: "数値リストから件数、合計、平均、中央値、最小、最大、母標準偏差を計算します。",
    faqs: [["どの区切りで入力できますか？", "改行、空白、カンマ区切りに対応します。"], privacyFaq],
  },
  {
    id: "bytes-converter", mode: "bytes-converter", family: "generalmore", category: "計算", categoryKey: "calculator",
    href: "/calculator/bytes/", name: "B・KB・MB・GB・TB変換",
    title: "データ容量単位変換｜B・KB・MB・GB・TB",
    description: "B、KB、MB、GB、TBを1024基準で相互変換します。",
    faqs: [["1000基準ですか？", "いいえ。このツールは1KB=1024Bとして計算します。"], privacyFaq],
  },
  {
    id: "aspect-ratio", mode: "aspect-ratio", family: "generalmore", category: "計算", categoryKey: "calculator",
    href: "/calculator/aspect-ratio/", name: "アスペクト比計算",
    title: "アスペクト比計算｜幅と高さから16:9などを算出",
    description: "幅と高さから最簡比のアスペクト比と幅÷高さの値を計算します。",
    faqs: [["1920×1080ならどうなりますか？", "16:9として表示します。"], privacyFaq],
  },
  {
    id: "video-compress", mode: "compress", family: "video", category: "動画", categoryKey: "video",
    href: "/video/compress/", name: "動画圧縮",
    title: "動画圧縮ツール｜MP4をブラウザ内で軽量化",
    description: "動画をブラウザ内で再エンコードし、画質を選びながらファイル容量を小さくします。",
    faqs: [["どのくらい圧縮できますか？", "元動画や選択した圧縮レベルによって変わります。標準では画質と容量のバランスを取って圧縮します。"], ["動画はサーバーへ送信されますか？", "いいえ。動画ファイル自体は送信せず、ブラウザ内のFFmpegで処理します。"]],
  },
  {
    id: "video-to-mp3", mode: "to-mp3", family: "video", category: "動画", categoryKey: "video",
    href: "/video/to-mp3/", name: "動画 → MP3変換",
    title: "動画をMP3に変換｜音声をブラウザ内で抽出",
    description: "動画ファイルから音声を抽出し、128〜320kbpsのMP3として保存します。",
    faqs: [["音質は選べますか？", "はい。128、192、256、320kbpsから選択できます。"], ["動画はサーバーへ送信されますか？", "いいえ。動画ファイル自体は送信せず、ブラウザ内のFFmpegで処理します。"]],
  },
  {
    id: "pdf-merge", mode: "merge", family: "pdf", category: "PDF", categoryKey: "pdf",
    href: "/pdf/merge/", name: "PDF結合",
    title: "PDF結合ツール｜複数PDFを無料で1つに",
    description: "複数のPDFを選択順に結合し、1つのPDFとして保存します。",
    faqs: [["PDFはアップロードされますか？", "いいえ。PDFの読み込みと結合はブラウザ内で処理します。"], privacyFaq],
  },
  {
    id: "pdf-split", mode: "split", family: "pdf", category: "PDF", categoryKey: "pdf",
    href: "/pdf/split/", name: "PDF分割・ページ抽出",
    title: "PDF分割・ページ抽出｜ページ範囲を指定",
    description: "PDFのページ範囲を指定し、複数PDFへ分割してZIPで保存します。",
    faqs: [["ページ範囲はどう指定しますか？", "1-3,4-6,8 のようにカンマ区切りで指定できます。"], privacyFaq],
  },  {
    id: "pdf-to-images", mode: "to-images", family: "pdf", category: "PDF", categoryKey: "pdf",
    href: "/pdf/to-images/", name: "PDF → PNG画像変換",
    title: "PDFをPNG画像に変換｜ページごとに保存",
    description: "PDF各ページをPNG画像へ変換し、ZIPでまとめて保存します。",
    faqs: [["複数ページも変換できますか？", "はい。全ページを順番にPNG化します。"], privacyFaq],
  },
  {
    id: "qr-generate", mode: "generate", family: "qr", category: "QRコード", categoryKey: "qr",
    href: "/qr/generate/", name: "QRコード生成",
    title: "QRコード生成｜URL・テキストから無料作成",
    description: "URLやテキストからQRコードを生成し、PNGで保存できます。",
    faqs: [["日本語もQRコードにできますか？", "はい。日本語を含むテキストにも対応します。"], privacyFaq],
  },
  {
    id: "qr-read", mode: "read", family: "qr", category: "QRコード", categoryKey: "qr",
    href: "/qr/read/", name: "QRコード読み取り",
    title: "QRコード読み取り｜画像から内容を解析",
    description: "QRコード画像を選択し、ブラウザ内で内容を読み取ります。",
    faqs: [["撮影済みの画像から読み取れますか？", "はい。PNG・JPG・WebP画像を選択できます。"], privacyFaq],
  },
  {
    id: "uuid-generator", mode: "uuid", family: "developer", category: "開発者", categoryKey: "developer",
    href: "/developer/uuid/", name: "UUID生成",
    title: "UUID v4生成ツール｜まとめて無料生成",
    description: "ブラウザの暗号学的乱数を使ってUUID v4をまとめて生成します。",
    faqs: [["UUID v4ですか？", "はい。crypto.randomUUID()を利用してUUID v4を生成します。"], privacyFaq],
  },
  {
    id: "unix-time", mode: "unix-time", family: "developer", category: "開発者", categoryKey: "developer",
    href: "/developer/unix-time/", name: "Unix時間変換",
    title: "Unix時間・日時変換｜秒・ミリ秒対応",
    description: "Unixタイムスタンプと日時を相互変換します。秒・ミリ秒を自動判定します。",
    faqs: [["秒とミリ秒の両方に対応しますか？", "はい。桁数をもとに自動判定します。"], privacyFaq],
  },
];

export const extraToolByPath = new Map(extraTools.map((tool) => [tool.href, tool]));
